### ISSUE TITLE
What mean is this？

### ISSUE THREAD

**Issue by wyfang** [Marc3842h/Titan#104]
![qq20181116-163557](https://user-images.githubusercontent.com/17900420/48608705-cea7e300-e9bd-11e8-9b16-a414c4930904.png)

**Comment by rishav394** [comment]
Don;t run titan as an Administrator

**Comment by wyfang** [comment]
Fine.

Does anyone know that an account with a CSGO game is required to use it? For example, if you have a version of CSGO China（ csgo.com.cn ）, can use it?

**Comment by Marc3842h** [comment]
As CS:GO is now free to play, your question obsoletes itself.
