### ISSUE TITLE
Automatic acquisition of a CS:GO free license

### ISSUE THREAD

**Issue by James94665** [Marc3842h/Titan#106]
Could you guys add a feature on Titan to automatically start csgo before reporting or commending? Since it takes a long time to run csgo on each acc before adding them to titan

**Comment by MaRRk0** [comment]
@Marc3842h People waiting this function, please deal with it ❤️

**Comment by Marc3842h** [comment]
As mentioned by @KillaBoi, this has been implemented starting with 5a3e899 and fully working with 31d5c81. In order to use the new feature, please build from source or wait for the next release 1.7.0 which will contain this feature.
