### ISSUE TITLE
The steam rate limit

### ISSUE THREAD

**Issue by feshaaak** [Marc3842h/Titan#109]
## Description

I am getting error

## Reproduction Steps

Did all right

## Errors

20:19:24 [Main] ERROR ThreadManager - The Steam Rate Limit has been reached. Please try again in a few minutes.

## System Information

W10
Titan 1.6.1

**Comment by Marc3842h** [comment]
You reached the Steam Rate Limit, can't be anything done against it except using a VPN or Proxy or waiting until you're no longer rate limited.
