### ISSUE TITLE
Cant open .exe

### ISSUE THREAD

**Issue by zorroxa** [Marc3842h/Titan#111]
Titan - Titan is running as administrator or root.
22:16:45 [Main] ERROR Titan - This is not supported. Titan will refuse to start until you start it as normal user. If you are unable to do this for any reason, start Titan with the --admin option to force the usage of administrator rights.

How do i start as --admin?

**Comment by fredddii** [comment]
Hello. My name is Philip and I work with Titan Inc. and I will gladly assist you with your issue.

As the message advises, you will not want to run the software as an administrator. This is simply good software practice that we like to enforce.

If you are running Windows Vista or higher, it is advisable to keep User Access Control enabled at a safe level. Instructions to re-enable this feature may be found here:
https://docs.microsoft.com/en-us/intune-user-help/you-need-to-enable-uac-windows

If you are running the software on Windows XP or lower it is recommended to do regular work on a normal user account while you keep a separate administrator account on the side.

Thank for your putting your faith in Titan Inc. software.

**Comment by fredddii** [comment]
Right click on the software executable and pick the option "Properties". Then move to the tab "Compatibility". Are any options marked in there?

**Comment by Marc3842h** [comment]
Hello. My name is Marc and I'm the lead developer of Titan Inc. and will gladly assist you with your issue.

As the message advises, you will not want to run the software as an administrator. This is simply good software practice that we like to enforce.

As indicated by your message, you have failed to deactivate possible administrator accounts so I will guide you throught the process of running Titan as administrator.

Please note that this is not advised and is unsupported.

To do this, please open a terminal (type in search `cmd.exe` and press Enter) or right click on your Windows start menu where you can see the menu point "PowerShell". Once you located it, click on it.

After you have done this, navigate to the directory where your `Titan.exe` file is stored by using the `cd` command. For example, if Titan.exe is in `C:\Users\Marc\Titan`, you can change to that directory by typing `cd C:\Users\Marc\Titan`.

After that you can simply run the following command `Titan.exe --admin`. Please note the `--admin` option. This flag enables running Titan as administrator, again this is not advised and is unsupported.

Thank you.

**Comment by zorroxa** [comment]
Wow! That worked like a charm!
Thnx for really fast and helpful advises!
Have a great day u 2 <3

**Comment by mashiro66** [comment]
Thanks
