### ISSUE TITLE
Can't build (PowerShell)

### ISSUE THREAD

**Issue by PedroLima14** [Marc3842h/Titan#116]
I can't build in PowerShell, when i do the command (.\build.ps1) this error happens:

Preparing to run build script...
Running build script...

========================================
Clean
========================================

========================================
Restore-NuGet-Packages
========================================
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin'.
All packages listed in packages.config are already installed.

========================================
Set-Version-To-Current-Git-Hash
========================================
Building for Git Hash: 7b45388, ,

========================================
Build
========================================
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 12/30/2018 2:52:27 AM.
Project "C:\Users\pedro\Titan\Titan.sln" on node 1 (Build target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Users\pedro\Titan\Titan.sln" (1) is building "C:\Users\pedro\Titan\Titan\Titan.csproj" (2) on node 1 (defau
lt targets).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.ta
rgets(322,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuil
d\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is co
rrect, and that the file exists on disk. [C:\Users\pedro\Titan\Titan\Titan.csproj]
Done Building Project "C:\Users\pedro\Titan\Titan\Titan.csproj" (default targets) -- FAILED.

Project "C:\Users\pedro\Titan\Titan.sln" (1) is building "C:\Users\pedro\Titan\TitanTest\TitanTest.csproj" (3) on node
1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.ta
rgets(322,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuil
d\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is co
rrect, and that the file exists on disk. [C:\Users\pedro\Titan\TitanTest\TitanTest.csproj]
Done Building Project "C:\Users\pedro\Titan\TitanTest\TitanTest.csproj" (default targets) -- FAILED.

Done Building Project "C:\Users\pedro\Titan\Titan.sln" (Build target(s)) -- FAILED.

Build FAILED.

"C:\Users\pedro\Titan\Titan.sln" (Build target) (1) ->
"C:\Users\pedro\Titan\Titan\Titan.csproj" (default target) (2) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.
targets(322,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBu
ild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is
correct, and that the file exists on disk. [C:\Users\pedro\Titan\Titan\Titan.csproj]

"C:\Users\pedro\Titan\Titan.sln" (Build target) (1) ->
"C:\Users\pedro\Titan\TitanTest\TitanTest.csproj" (default target) (3) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.
targets(322,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBu
ild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is
correct, and that the file exists on disk. [C:\Users\pedro\Titan\TitanTest\TitanTest.csproj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.21
An error occurred when executing task 'Build'.
Error: One or more errors occurred.
        MSBuild: Process returned an error (exit code 1).
PS C:\Users\pedro\Titan>

**Comment by Marc3842h** [comment]
Install VS Build Tools or use release 1.6.1

**Comment by PedroLima14** [comment]
How do i download 1.6.1?

**Comment by Marc3842h** [comment]
Release tab
