### ISSUE TITLE
Error commending

### ISSUE THREAD

**Issue by zeywi** [Marc3842h/Titan#117]
When i try to commend bot it says that it couldnt do it. Help?

04:11:34 [Main] INFORMATION Quartz.NET Scheduler - Default Quartz.NET properties loaded from embedded resource file
04:11:34 [Main] DEBUG Quartz.NET Scheduler - TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
04:11:34 [Main] INFORMATION Quartz.NET Scheduler - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
04:11:34 [Main] INFORMATION Quartz.NET Scheduler - Quartz Scheduler v."3.0.4.0" created.
04:11:34 [Main] INFORMATION Quartz.NET Scheduler - RAMJobStore initialized.
04:11:34 [Main] INFORMATION Quartz.NET Scheduler - Scheduler meta-data: Quartz Scheduler (v3.0.4.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

04:11:34 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler 'DefaultQuartzScheduler' initialized
04:11:34 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler version: 3.0.4.0
04:11:34 [Main] INFORMATION Quartz.NET Scheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
04:11:34 [Main] INFORMATION Titan - No valid verb has been provided while parsing. Opening UI...
04:11:34 [Main] DEBUG AccountManager - Titan Account Manager initialized on "4.11". (1546481494)
04:11:34 [Main] DEBUG GC - zeywreportbot98 (Unprotected) - Successfully initialized account object for "zeywreportbot98".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywreportbot98" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] DEBUG GC - zeywreportbot97 (Unprotected) - Successfully initialized account object for "zeywreportbot97".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywreportbot97" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] DEBUG GC - zeywreportbot96 (Unprotected) - Successfully initialized account object for "zeywreportbot96".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywreportbot96" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] DEBUG GC - zeywreportbot95 (Unprotected) - Successfully initialized account object for "zeywreportbot95".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywreportbot95" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] DEBUG GC - zeywalias1 (Unprotected) - Successfully initialized account object for "zeywalias1".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywalias1" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] DEBUG GC - zeywalias2 (Unprotected) - Successfully initialized account object for "zeywalias2".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywalias2" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] DEBUG GC - zeywalias3 (Unprotected) - Successfully initialized account object for "zeywalias3".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywalias3" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] DEBUG GC - zeywalias4 (Unprotected) - Successfully initialized account object for "zeywalias4".
04:11:34 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: "zeywalias4" / Password: "" / Sentry: False / Enabled: True
04:11:34 [Main] WARNING AccountManager - Less than 11 (only 8) accounts have been parsed. Atleast 11 accounts are required to get a target into Overwatch.
04:11:34 [Main] INFORMATION AccountManager - Account file has been successfully parsed. 8 accounts have been parsed. Details: [{Index=0, Count=8}]
04:11:34 [Main] DEBUG AccountManager - Index #-1 hasn't expired yet. It will expire on "13.57".
04:11:34 [Main] DEBUG AccountManager - Using index #0 for botting.
04:11:34 [Main] DEBUG SWAHandle - Received key from "steamapi.key" file: ""
04:11:35 [Main] INFORMATION SWAHandle - Steam Web API is valid and will be used.
04:11:35 [Main] INFORMATION Titan - Hello and welcome to Titan "v1.6.1-".
04:11:35 [Main] DEBUG Titan - Startup done. Active threads: 58
04:11:35 [Main] DEBUG Quartz.NET Scheduler - Producing instance of Job 'Titan.Victim Tracker Job', class=Titan.Logging.VictimTracker
04:11:35 [Main] DEBUG Quartz.NET Scheduler - Calling Execute on job Titan.Victim Tracker Job
04:11:35 [null] INFORMATION VictimTracker - Checking all victims if they have bans on record.
04:11:35 [null] DEBUG VictimTracker - Victims: []
04:11:35 [Main] DEBUG Quartz.NET Scheduler - Trigger instruction : NoInstruction
04:11:42 [Main] INFORMATION CommendTab - Starting commending of 76561198064438170.
04:11:42 [Main] DEBUG AccountManager - Starting botting using index 0.
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywreportbot98".
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywreportbot97".
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywreportbot96".
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywreportbot95".
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywalias1".
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywalias2".
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywalias3".
04:11:42 [Main] DEBUG ThreadManager - Starting commending thread for "[U:1:104172442]" using account "zeywalias4".
04:11:42 [Main] DEBUG AccountManager - Successfully wrote index file.
04:11:42 [Main] DEBUG AccountManager - Index #0 has been used. It will be unlocked on "16.11.42". Suggesting index #1 for next botting session.
04:11:4804:11:48 [ [MainMain] ] DEBUGDEBUG  GC - zeywreportbot97 (Unprotected)GC - zeywreportbot96 (Unprotected) -  - Disconnected from Steam. Retrying in 5 seconds... (Disconnected from Steam. Retrying in 5 seconds... (11/5)/5)

04:11:49 [Main] DEBUG GC - zeywreportbot98 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (1/5)
04:11:51 [Main] DEBUG GC - zeywalias2 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (1/5)
04:11:52 [Main] DEBUG GC - zeywreportbot95 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (1/5)
04:11:52 [Main] DEBUG GC - zeywalias1 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (1/5)
04:11:52 [Main] DEBUG GC - zeywalias4 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (1/5)
04:11:52 [Main] DEBUG GC - zeywalias3 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (1/5)
04:11:53 [Main] 04:11:53DEBUG [ MainGC - zeywreportbot97 (Unprotected)]  - DEBUGDisconnected from Steam. Retrying in 5 seconds... ( 2GC - zeywreportbot96 (Unprotected)/5)
 - Disconnected from Steam. Retrying in 5 seconds... (2/5)
04:11:54 [Main] DEBUG GC - zeywreportbot98 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (2/5)
04:11:56 [Main] DEBUG GC - zeywalias2 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (2/5)
04:11:57 [Main] DEBUG GC - zeywreportbot95 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (2/5)
04:11:57 [Main] DEBUG GC - zeywalias1 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (2/5)
04:11:57 [Main] DEBUG GC - zeywalias4 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (2/5)
04:11:57 [Main] DEBUG GC - zeywalias3 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (2/5)
04:11:58 [04:11:58Main [] Main] DEBUG DEBUGGC - zeywreportbot97 (Unprotected)  - GC - zeywreportbot96 (Unprotected)Disconnected from Steam. Retrying in 5 seconds... ( - Disconnected from Steam. Retrying in 5 seconds... (33/5)/5)

04:11:59 [Main] DEBUG GC - zeywreportbot98 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (3/5)
04:12:01 [Main] DEBUG GC - zeywalias2 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (3/5)
04:12:02 [Main] DEBUG04:12:02 GC - zeywreportbot95 (Unprotected) [ - Disconnected from Steam. Retrying in 5 seconds... (Main3] /5)DEBUG
 GC - zeywalias1 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (3/5)
04:12:02 [Main] DEBUG GC - zeywalias4 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (3/5)
04:12:02 [Main] DEBUG GC - zeywalias3 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (3/5)
04:12:0304:12:03 [Main]  [DEBUGMain ] GC - zeywreportbot97 (Unprotected)DEBUG -  Disconnected from Steam. Retrying in 5 seconds... (GC - zeywreportbot96 (Unprotected)4 - /5)Disconnected from Steam. Retrying in 5 seconds... (
4/5)
04:12:04 [Main] DEBUG GC - zeywreportbot98 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (4/5)
04:12:06 [Main] DEBUG GC - zeywalias2 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (4/5)
04:12:07 [04:12:07Main] DEBUG [ MainGC - zeywreportbot95 (Unprotected)]  - DEBUG Disconnected from Steam. Retrying in 5 seconds... (GC - zeywalias1 (Unprotected) - 4Disconnected from Steam. Retrying in 5 seconds... (/5)
4/5)
04:12:07 [Main] DEBUG GC - zeywalias4 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (4/5)
04:12:07 [Main] DEBUG GC - zeywalias3 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (4/5)
04:12:08 [Main04:12:08] DEBUG GC - zeywreportbot97 (Unprotected) [ - MainDisconnected from Steam. Retrying in 5 seconds... (] 5DEBUG/5)
GC - zeywreportbot96 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (5/5)
04:12:09 [Main] DEBUG GC - zeywreportbot98 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (5/5)
04:12:11 [Main] DEBUG GC - zeywalias2 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (5/5)
04:12:1204:12:12 [ [MainMain] ] DEBUGDEBUG  GC - zeywreportbot95 (Unprotected)GC - zeywalias1 (Unprotected) -  - Disconnected from Steam. Retrying in 5 seconds... (Disconnected from Steam. Retrying in 5 seconds... (55/5)/5)

04:12:12 [Main] DEBUG GC - zeywalias4 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (5/5)
04:12:12 [Main] DEBUG GC - zeywalias3 (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (5/5)
04:12:1304:12:13 [ [MainMain] ] DEBUGDEBUG  GC - zeywreportbot97 (Unprotected)GC - zeywreportbot96 (Unprotected) -  - Successfully disconnected from Steam.
Successfully disconnected from Steam.
04:12:14 [Main] DEBUG GC - zeywreportbot98 (Unprotected) - Successfully disconnected from Steam.
04:12:16 [Main] DEBUG GC - zeywalias2 (Unprotected) - Successfully disconnected from Steam.
04:12:16 [Main] ERROR ThreadManager - FAIL! Titan was not able to commend target 76561198064438170.
04:12:1704:12:17 [ [Main] MainDEBUG]  DEBUGGC - zeywreportbot95 (Unprotected)  - GC - zeywalias1 (Unprotected)Successfully disconnected from Steam.
 - Successfully disconnected from Steam.
04:12:17 [Main] DEBUG GC - zeywalias4 (Unprotected) - Successfully disconnected from Steam.
04:12:17 [Main] DEBUG GC - zeywalias3 (Unprotected) - Successfully disconnected from Steam.

**Comment by jaalmecigac** [comment]
Maybe steam Block Your IP - Steam web key, try again in 50 minutes.
