### ISSUE TITLE
Cannot commend; license error

### ISSUE THREAD

**Issue by wintersim** [Marc3842h/Titan#120]
## Description

The new 'auto-accquire cs:go license' feature is not working for me on accounts that aleady own cs:go. I'm currently on linux, but I'm sure that this is not the cause of the problem.

## Reproduction Steps

1. Start Titan (mono Titan.exe)
2. Add account that already owns cs:go
3. Click on commend tab, enter Steam-ID, select correct index
4. Click on 'Commend' button

## Errors

```bash
15:36:00 [Main] ERROR GC - xxxxx (Protected) - Unable to request free license for app 730. Aborting.
15:36:00 [Main] DEBUG GC - xxxxx (Protected) - Successfully disconnected from Steam.
15:36:00 [Main] ERROR ThreadManager - FAIL! Titan was not able to commend target xxxxxxxxxxxxxxxxxx.

```

## System Information

**Operating System**:  Ubuntu 18.10 (All up to date)
**Titan version**: 1.6.1-e46055d

**Comment by LemuelKL** [comment]
Does not work on my Windows 10 machine too, same commit version.

**Comment by Marc3842h** [comment]
This is now fixed.
