### ISSUE TITLE
Can't commend

### ISSUE THREAD

**Issue by PedroLima14** [Marc3842h/Titan#124]
## Description

I can't use the commend bot, i click in commend and doesn't commend in cs:go and gets cooldown.

## Reproduction Steps

1. Put the steam id
2. Click in commend
3. ...

## Errors

Console:
18:30:34 [Main] DEBUG GC - pedrolimabot1 (Protected) - Successfully connected to Steam. Logging in...
18:30:34 [Main] DEBUG GC - pedrolimabot1 (Protected) - Found previous Sentry file. Hashing it and sending it to Steam...18:30:34 [Main] DEBUG Sentry - pedrolimabot1 - Hash for sentry file found: "JjKPgbfc7giEXYM3C8YiOx2KMew="
18:30:34 [Main] DEBUG Login Key - pedrolimabot1 - Received login key from key file: "S0P1qqfZRG14HyN4AVo"
18:30:34 [Main] DEBUG GC - pedrolimabot1 (Protected) - Logging in with Auth Code: null / 2FA Code null / Hash: "JjKPgbfc7giEXYM3C8YiOx2KMew=" / LoginID: 709042790 / LoginKey: "S0P1qqfZRG14HyN4AVo"
18:30:35 [Main] DEBUG GC - pedrolimabot1 (Protected) - Successfully logged in. Registering that we're playing app 730...18:30:35 [Main] DEBUG GC - pedrolimabot6 (Protected) - Successfully connected to Steam. Logging in...
18:30:35 [Main] DEBUG GC - pedrolimabot6 (Protected) - Found previous Sentry file. Hashing it and sending it to Steam...18:30:35 [Main] DEBUG Sentry - pedrolimabot6 - Hash for sentry file found: "BjeysG5TXVXbg5UUQernTnm5NZs="
18:30:35 [Main] DEBUG Login Key - pedrolimabot6 - Received login key from key file: "UmAuYnqTGCdhPGP7Hk8"
18:30:35 [Main] DEBUG GC - pedrolimabot6 (Protected) - Logging in with Auth Code: null / 2FA Code null / Hash: "BjeysG5TXVXbg5UUQernTnm5NZs=" / LoginID: 2820362494 / LoginKey: "UmAuYnqTGCdhPGP7Hk8"
18:30:36 [Main] DEBUG GC - pedrolimabot6 (Protected) - Successfully logged in. Registering that we're playing app 730...18:30:36 [Main] DEBUG GC - pedrolimabot2 (Protected) - Successfully connected to Steam. Logging in...
18:30:36 [Main] DEBUG GC - pedrolimabot2 (Protected) - Found previous Sentry file. Hashing it and sending it to Steam...18:30:36 [Main] DEBUG Sentry - pedrolimabot2 - Hash for sentry file found: "e7dp/UWrJ+JsEsNfLouSqCLTjnw="
18:30:36 [Main] DEBUG Login Key - pedrolimabot2 - Received login key from key file: "srhFYksafJyB5HpuASo"
18:30:36 [Main] DEBUG GC - pedrolimabot2 (Protected) - Logging in with Auth Code: null / 2FA Code null / Hash: "e7dp/UWrJ+JsEsNfLouSqCLTjnw=" / LoginID: 1532147566 / LoginKey: "srhFYksafJyB5HpuASo"
18:30:37 [Main] DEBUG GC - pedrolimabot2 (Protected) - Successfully logged in. Registering that we're playing app 730...18:30:37 [Main] DEBUG GC - pedrolimabot1 (Protected) - Successfully registered app 730. Sending client hello to gc services.
18:30:37 [Main] DEBUG GC - pedrolimabot1 (Protected) - Received new login key: "dYnlvAne3IRG1XXV13M"
18:30:37 [Main] DEBUG GC - pedrolimabot5 (Protected) - Successfully connected to Steam. Logging in...
18:30:37 [Main] DEBUG GC - pedrolimabot5 (Protected) - Found previous Sentry file. Hashing it and sending it to Steam...18:30:37 [Main] DEBUG Sentry - pedrolimabot5 - Hash for sentry file found: "d/C3bwlubd2+y9q7aiR6Q0RKAKs="
18:30:37 [Main] DEBUG Login Key - pedrolimabot5 - Received login key from key file: "wb/zu+TNbXXy4/fGaL0"
18:30:37 [Main] DEBUG GC - pedrolimabot5 (Protected) - Logging in with Auth Code: null / 2FA Code null / Hash: "d/C3bwlubd2+y9q7aiR6Q0RKAKs=" / LoginID: 2932173789 / LoginKey: "wb/zu+TNbXXy4/fGaL0"
18:30:38 [Main] DEBUG GC - pedrolimabot4 (Protected) - Successfully connected to Steam. Logging in...
18:30:38 [Main] DEBUG GC - pedrolimabot4 (Protected) - Found previous Sentry file. Hashing it and sending it to Steam...18:30:38 [Main] DEBUG Sentry - pedrolimabot4 - Hash for sentry file found: "r4+jYBxL+b1xJAmwTKUiKLmG1sk="
18:30:38 [Main] DEBUG Login Key - pedrolimabot4 - Received login key from key file: "BQEkiZO899Q2XY6KDqY"
18:30:38 [Main] DEBUG GC - pedrolimabot4 (Protected) - Logging in with Auth Code: null / 2FA Code null / Hash: "r4+jYBxL+b1xJAmwTKUiKLmG1sk=" / LoginID: 2144923708 / LoginKey: "BQEkiZO899Q2XY6KDqY"
18:30:38 [Main] DEBUG GC - pedrolimabot3 (Protected) - Successfully connected to Steam. Logging in...
18:30:38 [Main] DEBUG GC - pedrolimabot3 (Protected) - Found previous Sentry file. Hashing it and sending it to Steam...18:30:38 [Main] DEBUG Sentry - pedrolimabot3 - Hash for sentry file found: "XhPWlXne9E2Qx1FSCiZTIzYahDo="
18:30:38 [Main] DEBUG Login Key - pedrolimabot3 - Received login key from key file: "tlFO53ZfmeuFDd92XJc"
18:30:38 [Main] DEBUG GC - pedrolimabot3 (Protected) - Logging in with Auth Code: null / 2FA Code null / Hash: "XhPWlXne9E2Qx1FSCiZTIzYahDo=" / LoginID: 213906762 / LoginKey: "tlFO53ZfmeuFDd92XJc"
18:30:38 [Main] DEBUG GC - pedrolimabot6 (Protected) - Successfully registered app 730. Sending client hello to gc services.
18:30:38 [Main] DEBUG GC - pedrolimabot6 (Protected) - Received new login key: "GDNAlJzM1FsrbygYY4g"
18:30:38 [Main] DEBUG GC - pedrolimabot5 (Protected) - Successfully logged in. Registering that we're playing app 730...18:30:38 [Main] DEBUG GC - pedrolimabot4 (Protected) - Successfully logged in. Registering that we're playing app 730...18:30:38 [Main] DEBUG GC - pedrolimabot3 (Protected) - Successfully logged in. Registering that we're playing app 730...18:30:39 [Main] DEBUG GC - pedrolimabot2 (Protected) - Successfully registered app 730. Sending client hello to gc services.
18:30:39 [Main] DEBUG GC - pedrolimabot2 (Protected) - Received new login key: "IA+MSCEd6uwTU4p1mgg"
18:30:40 [Main] DEBUG GC - pedrolimabot5 (Protected) - Successfully registered app 730. Sending client hello to gc services.
18:30:40 [Main] DEBUG GC - pedrolimabot5 (Protected) - Received new login key: "ESqZfVNSYkgidtLPYfk"
18:30:40 [Main] DEBUG GC - pedrolimabot4 (Protected) - Successfully registered app 730. Sending client hello to gc services.
18:30:40 [Main] DEBUG GC - pedrolimabot4 (Protected) - Received new login key: "1746Vj0r9qvk4ubCexg"
18:30:40 [Main] DEBUG GC - pedrolimabot3 (Protected) - Successfully registered app 730. Sending client hello to gc services.
18:30:40 [Main] DEBUG GC - pedrolimabot3 (Protected) - Received new login key: "Kh7N51Vr3/oZQk+hJ5w"

## System Information

**Operating System**: Windows 10
**Titan version**: 1.6.1-7b45388

**Comment by Marc3842h** [comment]
Hi your version `1.6.1-7b45388` is very outdated and thus not supported. Please upgrade to latest source code release `1.6.1-2b766d1`.

**Comment by PedroLima14** [comment]
Where i download it?

**Comment by Marc3842h** [comment]
You need to build it yourself or use a prebuilt source release by another person. (CC: @KillaBoi)

**Comment by PedroLima14** [comment]
How i do it?

**Comment by PedroLima14** [comment]
Where i put this?

**Comment by KillaBoi** [comment]
Wherever you want :)
its a prebuilt binary of the latest version

**Comment by PedroLima14** [comment]
Thanks man, i love you <3 It worked
