### ISSUE TITLE
Yo. The Steam Rate Limit has been reached. Please try again in a few minutes.

### ISSUE THREAD

**Issue by maxalove** [Marc3842h/Titan#126]
Heya. Is it possible to get around this limitation? Maybe you can add to Titan more than 1 api? 
I talking about autochecking api and when he get cd, he automatically using other api

Or proxy list...? i dont know

**Comment by maxalove** [comment]
> have same issue, can't commend 200+ times in one session
Ur right. If developer can release ApiList... eh

**Comment by fakeL1NK3R** [comment]
wait did you spend 5$ on each accounts? because from what I heard there's a requirement to get the API like spending 5$ and stuff

**Comment by maxalove** [comment]
Nope. Some accounts friends, who dont need api.
Some i get with other way)

**Comment by fakeL1NK3R** [comment]
Ah I see right right
well I guess afaik the best way to bypass it just change the api manually for now 
but for later update we dont know so...meh

**Comment by maxalove** [comment]
Now manually is the best way, yeap. And i write that issues for ApiList(like a proxylist)
Its will be nice and soooooooooooo faster, isnt it?

**Comment by Marc3842h** [comment]
The current way I will go about this issue is to implement a hard account limit within a certain timespan so that Steam no longer gets spammed and thus rate limited.

**Comment by maxalove** [comment]
And how do this? How about release in titan interval?

For ex: 1 commend - 1 sec
1000 commend will sended in 1000 sec

**Comment by Marc3842h** [comment]
@maxalove The current way to go about this issue for the current release is to simply use less accounts when botting, as Titan starts the botting for every selected account at once.

I'll implement soon a way where it limits the botting requests to something like 100 accounts for 10 seconds, then the next 100 etc.

**Comment by maxalove** [comment]
Okay. It will be nice. 
Issue can be closed

**Comment by Marc3842h** [comment]
No it can't. I'm keeping it open as a suggestion for the exact feature to be implemented.

**Comment by maxalove** [comment]
Oh. Okay.
And how about adding timer? If someone have more than 10k accs, he can just write a command so that the indexes are active at XX time.

**Comment by Marc3842h** [comment]
I don't understand your suggestion. Can you explain more clearly?

**Comment by maxalove** [comment]
Ehh.. i can try.
For example, we have ~20k accounts
And ~13 users who need commends
Can be write timer for accounts in auto-mode?

Today that 3 users, tomorrow other 3 users
And it will be done automatically, without user tracking..

in short - setting commands for bots with a timer
