### ISSUE TITLE
Self-compiled version is crashing

### ISSUE THREAD

**Issue by Weeeishy** [Marc3842h/Titan#13]
Hello,

So basically I compiled the src using Powershell and it built it with only 1 warning. However, when I open up Titan.exe, it crashes with the following error.

https://pastebin.com/GDPe0N5W

`Unhandled Exception: System.InvalidOperationException: Could not detect platform. Are you missing a platform assembly?
   at Eto.Platform.get_Detect()
   at Eto.Forms.Application..ctor()
   at Titan.UI.UIManager..ctor() in C:\Users\Yousef\desktop\titantest\Titan\UI\UIManager.cs:line 31
   at Titan.Titan.Main(String[] args) in C:\Users\Yousef\desktop\titantest\Titan\Titan.cs:line 82`

What could be the reason of that?

OS: Windows 10 pro 64-bit

**Comment by Marc3842h** [comment]
Do you have a Eto.Wpf.dll in the directory?

**Comment by Weeeishy** [comment]
No, it wasn't there

**Comment by Marc3842h** [comment]
It should be automaticly downloaded by Cake. Please give me the full Cake Log (before Build succeeded).

**Comment by Weeeishy** [comment]
There you go

https://pastebin.com/VDUTMzCW

**Comment by Marc3842h** [comment]
```cake
  Copying file from "C:\Users\Yousef\desktop\titantest\packages\Eto.Platform.Wpf.2.4.0-build1054\lib\net45\Eto.Wpf.dll"
   to "bin\Release\Eto.Wpf.dll".
```

It should have been copied, try to compile it again

**Comment by Weeeishy** [comment]
Complied, here is the new log: https://pastebin.com/5dMcuZkj

I can only see the eto.dll in my files.

**Comment by Weeeishy** [comment]
UPDATE: I just noticed that there are 2 BIN directories. One is located in Titan\bin and the other can be found in TitanTest\bin. I was using the second one for the whole time, I can see its missing few files by comparing it to the first path. Feel free to close the issue if that's intended.


Thank you for your time!

**Comment by Marc3842h** [comment]
Does the Eto.Wpf.dll exist in `C:\Users\Yousef\desktop\titantest\packages\Eto.Platform.Wpf.2.4.0-build1054\lib\net45\Eto.Wpf.dll`?
