### ISSUE TITLE
Convert.py not working

### ISSUE THREAD

**Issue by Xion4762** [Marc3842h/Titan#135]
## Description

Convert.py returns "A error occured while trying to convert the existing file."
Overwrites accounts.json with a blank file.

## Reproduction Steps

1. Run "python convert.py accounts.txt" in command line

## Errors

```bash
A error occured while trying to convert the existing file.
```

## System Information

**Operating System**: Windows 10 Pro
**Titan version**: 1.6.1

**Comment by FastPure** [comment]
i can't even find the convert.py script

**Comment by Marc3842h** [comment]
Your `accounts.txt` needs to be exclusively in the `username:password` format. If it isn't by just one line it'll fail.

**Comment by Xion4762** [comment]
I've found this error to be with python version. It was defaulting to Python 2 previously, which fails with this error:
![Python 2 error](https://i.imgur.com/AkQRj8P.png)
With Python 3, it seems to be functioning correctly, however does give a deprecation warning. 
![Python 3](https://i.imgur.com/73btUmi.png)
