### ISSUE TITLE
error to sign in

### ISSUE THREAD

**Issue by KingLifted** [Marc3842h/Titan#139]
22:20:07 [Main] DEBUG GC - username (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (1/5)
22:20:12 [Main] DEBUG GC - username (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (2/5)
22:20:17 [Main] DEBUG GC - username (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (3/5)
22:20:22 [Main] DEBUG GC - username (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (4/5)
22:20:27 [Main] DEBUG GC - username (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (5/5)
22:20:32 [Main] DEBUG GC - username (Unprotected) - Successfully disconnected from Steam.
22:20:32 [Main] ERROR ThreadManager - FAIL! Titan was not able to commend target xxxxxxxxxxxxxxxxx.

**Comment by Marc3842h** [comment]
Hey, please provide your operating system and Titan version.
