### ISSUE TITLE
Windows users don't receive a notification when a victim got banned

### ISSUE THREAD

**Issue by Marc3842h** [Marc3842h/Titan#14]
Windows users don't receive a notification as [Eto](https://github.com/picoe/Eto/blob/develop/Source/Eto.Wpf/Forms/NotificationHandler.cs#L27) hasn't implemented it **without** a TrayIcon. To workaround this issue, i'll implement a Windows-only TrayIcon that will display the notification.

**Comment by Marc3842h** [comment]
Implemented with commit 3f05167. This feature will be shipped with version 1.5.0. If you can't wait until then, please compile from source.

**Comment by Marc3842h** [comment]
It has now been properly implemented for both Linux and Windows.

Screenshots:

<sup><b>Windows (10)</b></sup>
![screenshot](https://user-images.githubusercontent.com/24739711/27094420-4878ef92-506a-11e7-8ee6-4051d8b9948b.png)

<sup><b>Linux</b> (Gnome + Arc-Dark)</sup>
![Notification](https://github.com/Marc3842h/Titan/blob/master/Titan/Resources/Notification.png)

**Comment by Weeeishy** [comment]
It looks hot af!

**Comment by Marc3842h** [comment]
Thanks.
