### ISSUE TITLE
convert.py is not working as it should

### ISSUE THREAD

**Issue by r4nd0wn** [Marc3842h/Titan#141]
## Description
Python convert script is not working properly (or my computer)
On my Microsoft Surface, its working with the same version of python...

## Reproduction Steps

1. Install Python 3.7 on my Pc
2. navigate to the Titan folder
3. paste my accounts.txt in the cloned titan folder
4. type in `python convert.py accounts.txt 10`

## Errors

```bash
C:\Users\jonas\Titan>python convert.py accounts.txt 10
Traceback (most recent call last):
  File "convert.py", line 9, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

## System Information

**Operating System**: Windows10 (1809)
**Titan version**: 1.6.1-0d3d790

**Comment by Marc3842h** [comment]
Hey, the `convert.py` has been deprecated and thus unsupported in favor of the `Import` feature available starting with commit 0d3d790, the one you're running.
