### ISSUE TITLE
 Support Program

### ISSUE THREAD

**Issue by KingLifted** [Marc3842h/Titan#143]
Hello again!

Is there a script to deactivate a list of new accounts protected by the vapor guard?

When new accounts are created, they are protected by e-mail.

It seems to me that accounts created less than a day do not require email confirmation. After that, she begins to ask.

Thank you and sorry for the inconvenience.

**Comment by Marc3842h** [comment]
Hey, Titan is currently not the right place to ask this question as we do not provide any account generation measures whatsoever. The only interaction with Steam Guard happens when logging in, asking for the SteamGuard code.

You have to contact the creator of your account generator.
