### ISSUE TITLE
hello KIND SIRE

### ISSUE THREAD

**Issue by lerdy** [Marc3842h/Titan#144]
HI INDEX SIZE CHOOSER PLEASE NEXT COMMIT YES? WHEN WILL IT BE DONE?
I HAVE TO HAVE IT BEFORE THIS GAME IS OVER OR I WILL NOT BE ABLE TO REPORT THIS GUY FOR RAGE HACKING

thanks\

am i going to be reported for this i hope not, theree will be consequences 
![9514abeef8e8e325388f53ffb3f74abb](https://user-images.githubusercontent.com/20730651/51777867-e8a33600-2163-11e9-85aa-452de20efd0a.png)

/s

**Comment by raspbianlike** [comment]
no

**Comment by Marc3842h** [comment]
yeet

**Comment by raspbianlike** [comment]
hi marc
wanna chat here

**Comment by Marc3842h** [comment]
![image](https://user-images.githubusercontent.com/24739711/51777950-b364fc80-20ff-11e9-8cdc-0cb61e806b25.png)

**Comment by lerdy** [comment]
delet this

**Comment by Marc3842h** [comment]
This issue has been flagged as abusive by myself and the GitHub Staff.

**This issue violates the Titan Code of Conduct**

Further violations will result in repository bans and GitHub abuse reports being filed.
