### ISSUE TITLE
VictimTracker - victims.json

### ISSUE THREAD

**Issue by fiskerface** [Marc3842h/Titan#145]
Hello
I banned a guy but VictimTracker does not pop up for me
Do I have to change the victims.json? I tried to put in steamID but did not worked..

my victims.json looks like:
{"victims":[]}

can som1 help me plz? :)
thx

**Comment by Marc3842h** [comment]
The victims.json format is

```js
{
    "victims": [
        {
            "steamid": 76561198224231904, // Replace this with target steamid64
            "timestamp": 1548700635 // Unix timestamp, feel free to keep at 0 if you don't know what it is
        }
    ]
}

**Comment by fiskerface** [comment]
thx

is it correct to have a steamapi.key data or should it be steamapikey.json?
how is the format for this type because Titan said

"[18:43:39 WARNING] SWAHandle 12 - No valid Web API key has been found. Skipping ban checking...
[18:43:39 WARNING] SWAHandle 12 - No valid Web API key has been found. Skipping ban checking...
[18:43:39 WARNING] SWAHandle 12 - No valid Web API key has been found. Skipping ban checking...
[18:43:39 DEBUG] SWAHandle 1 - Received key from "steamapi.key" file: "XXXXXXXXXXXXXXXXXXXXX"
[18:43:40 INFORMATION] SWAHandle 1 - Steam Web API is valid and will be used."

I checked my apikey and its the one in my steamapi.key data
steamapi.key format
`XXXXXXXXXXXXXXXXXXXXX`

**Comment by fiskerface** [comment]
>21:33:25 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler 'DefaultQuartzScheduler' initialized
21:33:25 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler version: 3.0.4.0
21:33:25 [Main] INFORMATION Quartz.NET Scheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
21:33:26 [Main] INFORMATION Titan - No valid verb has been provided while parsing. Opening UI...
21:33:26 [Main] DEBUG AccountManager - Titan Account Manager initialized on "21:33". (1548880406)
21:33:26 [Main] DEBUG Quartz.NET Scheduler - Producing instance of Job 'Titan.Victim Tracker Job', class=Titan.Logging.VictimTracker
21:33:26 [Main] DEBUG Quartz.NET Scheduler - Calling Execute on job Titan.Victim Tracker Job
21:33:26 [null] DEBUG VictimTracker - Checking all victims if they have bans on record.
21:33:26 [null] INFORMATION VictimTracker - Victims: ["Titan.Json.Victims+Victim", "Titan.Json.Victims+Victim", "Titan.Json.Victims+Victim"]
21:33:26 [Main] WARNING SWAHandle - No valid Web API key has been found. Skipping ban checking...
21:33:26 [Main] WARNING SWAHandle - No valid Web API key has been found. Skipping ban checking...
21:33:26 [Main] WARNING SWAHandle - No valid Web API key has been found. Skipping ban checking...
21:33:26 [Main] DEBUG Quartz.NET Scheduler - Trigger instruction : NoInstruction> 
dann loggt er die accs
>21:33:26 [Main] INFORMATION AccountManager - Account file has been successfully parsed. 11 accounts have been parsed. Details: [{Index=0, Count=11}]
21:33:26 [Main] DEBUG AccountManager - Index 0 has expired. It is now available for botting.
21:33:26 [Main] DEBUG AccountManager - Using index #0 for botting.
21:33:26 [Main] DEBUG SWAHandle - Received key from "steamapi.key" file: "XXXXXXXXXXXXXXXXXXXXXX"
21:33:27 [Main] INFORMATION SWAHandle - Steam Web API is valid and will be used.
21:33:27 [Main] INFORMATION Titan - Hello and welcome to Titan "v1.6.1".>

ein eingetragenener acc in der victims.json hat nen gameban aber ich krieg kein popup oder ieine msg :(

**Comment by Marc3842h** [comment]
**Please refrain from speaking german in the issues section, as noted in the [Code of Conduct file](https://github.com/Marc3842h/Titan/blob/master/CODE_OF_CONDUCT.md). This issue tracker is public and is supposed to be helpful to future users, which may very well don't speak german.**

The victim tracking is a scheduled thread run in the background at 15 minutes intervals. It does indeed get started before the Web API key is initialized but that wasn't a problem until now because the scheduler would be _usually_ later called than the main thread would've finished.

As your CPU seems to run insanely fast (or you just got a great scheduler, or just plain lucky), I'll post a fix for it in a few minutes.

**Comment by fiskerface** [comment]
can u please make a release fix?
I tried to install from source but I cant open Titan
PS installin everything and says 'titan is rdy to use' but it does not open

**Comment by trillex1337** [comment]
@Marc3842h  When I try to open the solution file I get the following message: One or more projects in the solution were not loaded correctly. Can you please help me?

**Comment by Marc3842h** [comment]
@fiskerface Until the feature is stablized, a official release won't be published on the releases tab. Some people may be friendly however and send you their own prebuilt versions of the latest Titan source code.

@45656456kawai Not yet as I'm unable to track progress on that issue as nobody has bothered to open a GitHub issue regarding it.

@trillex1337 Please read the [build guide](https://github.com/Marc3842h/Titan#option-2-from-source) before asking for any help, as you wouldn't have tried to open the solution file if you would've read it.

**Existing issues are not a place for asking for help. I will be locking this conversation to prevent more questions. If you find another issue or have more questions, please open a [new issue](https://github.com/Marc3842h/Titan/issues/new).**
