### ISSUE TITLE
Account Generator

### ISSUE THREAD

**Issue by PedroLima14** [Marc3842h/Titan#154]
Any free account generator working?

**Comment by r4nd0wn** [comment]
yes. i wont make promo on an Issue tracker, so just google yourselve or add me on steam (same name as here)

**Comment by Marc3842h** [comment]
Hey, this issue tracker is solely for the Titan **report & commend bot**. This does not include any account generator whatsoever, you are however invited to ask on our Discord (which is a more general place, not especially a issue tracker like here).

I will be locking this issue to prevent advertising.
