### ISSUE TITLE
Suggestion: cycle for commend

### ISSUE THREAD

**Issue by BoberMod** [Marc3842h/Titan#16]
Hello, can you add a cycle on commend menu? So that all accounts from all indexes commend steamid.

**Comment by Marc3842h** [comment]
This may cause problems with the SteamRateLimit, but I'll add it.

**Comment by Marc3842h** [comment]
Hey, your suggestion has been implemented with the new UI Redesign in #17. Please keep in mind that the new UI will most likely bring new bugs, so please report them in a new issue here on the issue tracker.

Your feature will be shipped with v1.5.0. If you can't wait until then, please compile from source.

Preview:
![newui](https://user-images.githubusercontent.com/24739711/27192453-b6da969c-51fb-11e7-84e4-06040006589e.png)
<sup>The "Use all accounts" checkbox also exists on the Commend tab.</sup>
