### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by Marc3842h** [Marc3842h/Titan#17]
To satisfy the suggestion #9 and #16 (etc.), I'll implement UI Redesign. 
It will be in the style of "Dr. Peppers Report Bot", but with the Titan features.

Preview screenshot:
![newui](https://user-images.githubusercontent.com/24739711/27188919-0442dfae-51f0-11e7-948e-7b5e8ed9ee8f.png)

**Comment by Marc3842h** [comment]
The new UI has been implemented as **Main** Form now in commit 9f654fe. The commits 7c5d870, e284844 and 4aa3982 have prepared the UI. 

TODO List until the shipping of the new UI:
- [x] Implement as Main Form
- [ ] Implement the Sub-UI's like "About" in the Menu Bar
- [ ] Fix Bugs introduced with the new UI

**Comment by 123top** [comment]
Maybe add custom amount for comments? wtf why you want to remove comments?

**Comment by Marc3842h** [comment]
I guess you're meaning "commends". I can implement that you can select a custom amount of accounts, that will be no problem. 

Also, the user in #5 suggested it, I don't know why he wants to remove it but I implemented it.

**Comment by TheRhanderson** [comment]
123top
And why do you care? If you were a salesperson, you would understand the reason very well.

**Comment by 123top** [comment]
@TheRhanderson I don't see your problem but to be honest i dont care :^)

@Marc3842h I mean like choose: give 11 good teacher, 7 good leader, 4 friendly
So I mean set a custom amount. Is this possible?

**Comment by Marc3842h** [comment]
@123top That is also possible, will also add.

**Comment by Weeeishy** [comment]
Is it possible to minimize to the hidden icons, if you know what I mean? I'd like to leave it open to check on the victims, but also don't want it to show up in the list of opened apps in the down-mid as I might close it accidentally. Thanks

**Comment by Marc3842h** [comment]
@Weeeishy Do you mean minimizing to the TrayIcon? This requires me to add a TrayIcon to Linux (on Windows it exists already), I can look into it.

**Comment by Weeeishy** [comment]
Yes, thats right. It would be very helpful!

**Comment by Marc3842h** [comment]
@123top I implemented the allowance of custom amount of bot accounts in commit dbd64a5. I'll implement the custom amount of specified options tommorow.

@Weeeishy This feature doesn't look like it has been implemented in Eto.Forms, I contacted the Eto.Forms developers on Gitter to find a solution.

**Comment by Marc3842h** [comment]
@Weeeishy Implemented. Your suggested feature will be shipped with v1.5.0. Please compile from source if you can't wait until then.

**Comment by Weeeishy** [comment]
Much appreciated man! Thank you.

**Comment by Marc3842h** [comment]
@123top Will consider your suggestion in release v1.6.0. Closing this issue as the new UI _should_ be stable.
