### ISSUE TITLE
No Work [Linux]

### ISSUE THREAD

**Issue by haxhash** [Marc3842h/Titan#192]
I cannot run Titan on Linux Mint Mate. I mean, it runs perfectly through Mono, and accounts are added, but at the moment when I want to praise myself or someone else, nothing comes of it, he says an error. 
Perhaps I configured something wrong, or the accounts do not fit, so what settings, accounts and requirements are needed for everything to work correctly?

**Comment by Misjudgments** [comment]
a bit late but if you don't know already
VALVE said they fixed that a while ago.
the only way now to commend bot is to open a server, make a plugin that adds bots and commend you.
@c3zs4r
