### ISSUE TITLE
Crashing upon reporting.

### ISSUE THREAD

**Issue by Weeeishy** [Marc3842h/Titan#2]
Hello,

I've followed the intrusction and got it working, but once I hit the "Bomb!" button it instantly crashes.

I got the following in the cmd

https://pastebin.com/Fi0RDzL5

What could be wrong?

**Comment by Marc3842h** [comment]
Are you using Windows or Linux?

**Comment by Weeeishy** [comment]
Oh sorry, I forgot to mention that. 

Windows 10.

**Comment by Marc3842h** [comment]
I'll set myself a Windows 10 virtual machine up and try to fix it tommorow. Thanks for reporting the issue.

**Comment by Weeeishy** [comment]
No worries. Thank you for your time. 👍

**Comment by Marc3842h** [comment]
Did you input a valid Steam Web API key?

**Comment by Weeeishy** [comment]
Yes, I did.

**Comment by Marc3842h** [comment]
Could you try it with the debug release below?
[Titan-debug.zip](https://github.com/Marc3842h/Titan/files/1001805/Titan-debug.zip)

**Comment by Weeeishy** [comment]
It's still crashing unfortunately.

**Comment by Marc3842h** [comment]
I enabled now debug mode in the package below. Please run it and see if it works. If it doesn't please also send your log messages from the console in a Pastebin (don't forget to remove the passwords from the log!).

[Titan-debug.zip](https://github.com/Marc3842h/Titan/files/1007601/Titan-debug.zip)

**Comment by Weeeishy** [comment]
This one is working absolutely fine. No crashes!

**Comment by Marc3842h** [comment]
Alright, closing this issue now. Please upgrade to the newest release as soon as it gets released. I'll reply when it got released.

**Comment by Marc3842h** [comment]
The latest release [v1.4.0](https://github.com/Marc3842h/Titan/releases/tag/v1.4.0) has been released yesterday. It includes the bugfix provided for this issue. If any more questions or issues come up, feel free to open another issue.

**Comment by Weeeishy** [comment]
Thanks for the headsup! I've downloaded it yesterday and it worked perfectly well, the guy I reported got banned within an hour.

Cheers
