### ISSUE TITLE
Hi, Im having some issues installing and running the program, Im using Ubuntu 16.04 here is my terminal logs:

### ISSUE THREAD

**Issue by iPredictable** [Marc3842h/Titan#20]
Hi, Im having issues installing and running Titan, I am using Ubuntu 16.04 my terminal is giving errors Logs: 
predictable@predictable:~/Titan$ chmod +x build.sh && ./build.sh
Downloading NuGet...
./build.sh: line 84: mono: command not found
Could not restore NuGet tools.
predictable@predictable:~/Titan$ Titan.exe (--target) (--mode) [--id] [--file]
bash: syntax error near unexpected token `--target'
predictable@predictable:~/Titan$

**Comment by Marc3842h** [comment]
Can you please fill out the complete template? Thanks.

**Comment by PredictEr** [comment]
Sorry fixed, can I add you on steam to ask you about this, I think its a more personal issue rather than one needed to be discussed here.

**Comment by Marc3842h** [comment]
yea, add me on Steam /id/Marc3842h

**Comment by Marc3842h** [comment]
The user didn't reply within 7 days, closing this issue.
