### ISSUE TITLE
it just crashes 

### ISSUE THREAD

**Issue by bigdaddy543** [Marc3842h/Titan#23]
you have any trubble shoot steps enter in window steam id press bomb then titan has stopped working 

this is what i have in accounts .json thing : 

{
    // Per index are maximum 11 accounts allowed. Begin a new index when a new account is required.
    "indexes": [
        {
            "accounts": [
                {
                    "username": "JOHNY2",
                    "password": "Password231432",
                },
            ]
        }
    ]

i press visual studio debug and says:
An unhandled exception of type 'System.Net.WebException' occurred in SteamKit2.dll

Additional information: The remote server returned an error: (400) Bad Request.

i have 1.4 of report bot i was useing askwrites but now it stoped working on my accounts all of a sudden so i realy need tital to pull through and work form me as i invested in 22 accounts to bann cheaters ;c

**Comment by ra1N1336** [comment]
you need to enter steam web api key

**Comment by Marc3842h** [comment]
Hi, did you input a valid Steam Web API key as @ra1N1336 already mentioned (does a `steamapi.key` exist and does it contain a valid Steam Web API key?)

**Comment by bigdaddy543** [comment]
IT DOSENT CRASH now but it cannot report with my accounts 
10:43:41 [Main] ERROR ThreadManager - Could not report 437934212 with account dabasi2.
10:43:41 [Main] ERROR ThreadManager - Could not report 437934212 with account dabasi4.

i put everything i said in past bin  https://pastebin.com/vZbPDHmU

**Comment by Marc3842h** [comment]
Are you using the latest release from the Releases tab or from source code compiled?

**Comment by bigdaddy543** [comment]
i put bits from different releces together

**Comment by Marc3842h** [comment]
That doesn't sound good to be honest, try to compile from source with the latest release and try again. I'm currently urging to fix the bugs with the latest source code and will then release v1.5.0

**Comment by bigdaddy543** [comment]
waw it works i am just retarded by puting code from the different versons together thanks for the help
