### ISSUE TITLE
BUG maybe

### ISSUE THREAD

**Issue by bigdaddy543** [Marc3842h/Titan#24]
when i press bomb it says message : 

15:21:17 [Main] INFORMATION ThreadManager - Successfully sent a report to 435944278 with account dabasi2.

but i can keep pressing bomb and out puts more of these messages with no 6 h cool down  but one time one of the messages said 
reported coformation id *********** but i only seen it do that once i have the 1.4 freom the releases tab i just addeded accopunts.json and the .key file  i am on win 10 

paste bin of full output https://pastebin.com/VFNxMaqa

**Comment by Marc3842h** [comment]
Hi, If I understood you right, you tried to report somebody with no 6h cooldown and then you got confirmation ID's but after that you no longer receive them? Its kind of hard to understand your English

**Comment by bigdaddy543** [comment]
nooo mayn it says : 
15:34:51 [Main] INFORMATION ThreadManager - Successfully sent a report to 435944278 with account dabasi20.

but not conformation id exept from one time where 1 account out of 11 sayed conformation id

**Comment by Marc3842h** [comment]
That is coming from the ThreadManager, the ThreadManager *never* receives a confirmation if the account was also successfully sent. You need to listen for any console output named "GC - <Accountname>"

**Comment by bigdaddy543** [comment]
yea i get no GC -  what is the cause of this

**Comment by Marc3842h** [comment]
You're using the 1.4.0 release, please try it again with the latest release compiled from the source code.

**Comment by bigdaddy543** [comment]
i compiled and use the different looking gui but no reports submited i think 
here is out put of prograrm https://pastebin.com/xUX9RnTE
