### ISSUE TITLE
development still in progress?

### ISSUE THREAD

**Issue by 123top** [Marc3842h/Titan#26]
I mean 1.4 is out like half a year now and it don't ban people anymore

**Comment by Marc3842h** [comment]
It doesn't ban people anymore? What? It _should_ be working, as I don't get any error reports.

Right now I'm suggesting **compiling** from source as Releases are outdated because working on the new UI takes time.

**Comment by 123top** [comment]
So I reported a spin botter and he is not banned.

How to compile? What do I need?

**Comment by Marc3842h** [comment]
Visual Studio 2017 with .NET Desktop Development selected in Installation Process should be enough.

Do you surely had 11 bots that haven't reported in the last 6 hour before you tried to bot him? Did you use Match ID? 

I personally had more success in getting cheaters banned using Match ID (rather than leaving it empty).

**Comment by BoberMod** [comment]
To send person to ban you need 11 reports = 11 accounts, delay between reports is 24 hours.
I recommend to use Match ID.
How to compile - https://github.com/Marc3842h/Titan#installation

**Comment by 123top** [comment]
I was one week on holiday so the delay was>24h. And I got 11 accounts for sure

**Comment by Marc3842h** [comment]
Did you report with Match ID or without?

**Comment by 123top** [comment]
with matchid of course, even during the match

**Comment by Marc3842h** [comment]
**I** never got good results when reporting during the match. Did you try re-botting him again? And how did you get the Match ID during the match

**Comment by BoberMod** [comment]
I often report during the match and and usually he get a ban. If you report during the game, there is more chance that he will go to Overwatch at the moment when he play rage (but I'm not sure).
ShareCode is not Match ID. You can get Match ID during the game -https://bitbucket.org/keepmind/csgo-report-commend-bot-gui/src/d398c44b42ea1a4e73ff361061ac51938ce2ccbf/GetMatchID.js?at=master&fileviewer=file-view-default

**Comment by 123top** [comment]
@Marc3842h The easiest way to get the matchid during the match: 
1. open csgo console while you search 
2. when it says confirming match in console there is something like: match_id=8123123123123123 (no real id)
3. profit

To my problem...in the past it worked allways like that and I got a lot of fgts banned

**Comment by Marc3842h** [comment]
A Match ID resolver has been implemented. It will be shipped with v1.5.0. I'm closing this issue as it doesn't seem like a bug with Titan at the moment. Please open _another_ issue if you still encouter issues with reporting.
