### ISSUE TITLE
The Steam Rate Limit has been reached. Please try again in a few minutes.

### ISSUE THREAD

**Issue by thestranger00** [Marc3842h/Titan#28]
hello

i added 33 accounts and used the commend bot but i only received 18 and then this error

The Steam Rate Limit has been reached. Please try again in a few minutes.

idk what it means hope you know and all those accounts were offline/inactive while using it in the program

**Comment by thestranger00** [comment]
also i cannot send commends it says "sending commends not possible"

i used 33 accounts i checked "use all accounts" and only got 18 commends im confused.

**Comment by thestranger00** [comment]
timed out. It was not possible to commend the target after 0 seconds.

**Comment by Marc3842h** [comment]
Yea you reached the Steam Rate Limit can't do anything about it

**Comment by thestranger00** [comment]
Which steam profile's  API key we supposed to use?

it ask for it every time i launch titan.

**Comment by Marc3842h** [comment]
http://steamcommunity.com/dev/apikey

Domain Name doesn't matter. You can even provide an email as Steam just wants the Domain for contact information in case of abuse.

**Comment by Marc3842h** [comment]
User didn't respond within 7 days, closing this issue.
