### ISSUE TITLE
Titan account issue

### ISSUE THREAD

**Issue by 123top** [Marc3842h/Titan#30]
Titan is unable to login, into the first account of accounts.json. I double checked everything and password and username is right. I can login with other reportbots, but on titan it can't login on the account.

**Comment by BoberMod** [comment]
Do you use steam idlers (ASF, hours boost, etc)?

**Comment by Marc3842h** [comment]
Please follow the issue template and provide any error logs, provide your OS, reproduction steps etc.

Does the account have SteamGuard enabled?

**Comment by Marc3842h** [comment]
Closing this issue as user didn't respond within 7 days.
