### ISSUE TITLE
some general reportbot problems?

### ISSUE THREAD

**Issue by smurfPrime** [Marc3842h/Titan#31]
It is nothin with an error....
the reportbots itself do not work... commends are working

but when I report raging guys (who never play more than 1 or 2 rage games) they do not get a BAN!
what did steam changed to the system? zoner is still working fine... but askwrite script is fixed.. like some others!
_wondering because I thought zoner is using askwrite-script_
# 
# need help!

titan says reportes were send but why no OW?  dont say shit like they did not were obvious enough!

using TItan v1.4.0 on win10

**additional information:**
I tried report instant after game with and without matchID
I tried report ingame last 5 rounds or less

sometimes it worked and the guy got banned... BUT I checked the profile and 1guy had commend from zonerbot.. I DONT THINK TITAN REPORTS ARE WORKING!
smth is really really wrong!!!

**some BANs**
2 guys got banned 4-5 days ago, I reported
`I got the blue message: Player u have recently reported got banned..`
I never report with my bot accounts (only with reportbot/Titan)
So the reports worked? Should!
But why some ppl do not get their BAN?
Too many ppl I reported did not got a BAN.

**Comment by smurfPrime** [comment]
I tried v1.5.0 but Titan crashes when loading UI.

`debugging dont work: Ausnahmefehler bei 0x00007FFD75DDFD0C (d3d9.dll) in Titan.exe: 0xC0000005: Zugriffsverletzung beim Schreiben an Position 0x0000000000000000`

`"00007FFD75DDFD0C  add         byte ptr [rax],al" `



titan.log
`[08:07:01` DEBUG] Titan @ 1 - Startup: Loading UI Manager, Victim Tracker, Account Manager and Ban Manager.
[08:07:02 DEBUG] Titan @ 1 - Startup: Registering Shutdown Hook.
[08:07:02 DEBUG] Titan @ 1 - Startup: Parsing accounts.json file.
[08:07:02 DEBUG] Titan @ 1 - Initializing Forms...
[08:07:02 DEBUG] Titan @ 1 - Startup: Loading Web API Key
[08:07:02 INFORMATION] Titan @ 1 - Hello and welcome to Titan v1.4.0-Dev.
[08:07:15 DEBUG] Titan @ 1 - Startup: Loading Serilog <-> Common Logging Bridge.
[08:07:15 DEBUG] Titan @ 1 - Startup: Loading Quartz.NET.
[08:07:16 DEBUG] Titan @ 1 - Startup: Refreshing Steam Universe list.
[08:07:16 DEBUG] Titan @ 1 - Startup: Parsing Command Line Arguments.
[08:07:16 INFORMATION] Titan @ 1 - The arguments --target and --mode were omitted - opening the UI.`

**Comment by Marc3842h** [comment]
This is interesting. You are right now not one out of 2 guys saying that. When I'm back from vacations, I'll investigate.

Does a error in the console occur when Titan crashes?

**Comment by smurfPrime** [comment]
last message in console
```
22:08:24 [Main] DEBUG GC - smurfXXX (Protected) - Successfully initialized account object for smurfXXX.
22:08:24 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: smurfXXX / Password: XXX / Sentry: false / Enabled: true
22:08:24 [Main] INFORMATION AccountManager - Account file has been successfully parsed. 11 accounts have been parsed. Details: [{Index=0, Count=11}]
22:08:24 [Main] DEBUG AccountManager - Using index #0 for botting.
22:08:24 [Main] DEBUG Titan - Initializing Forms...
22:08:25 [Main] DEBUG Titan - Startup: Loading Web API Key
22:08:25 [Main] DEBUG WebAPIKeyResolver - Using Steam API Key XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX for the Steam Web API.
22:08:25 [Main] INFORMATION Titan - Hello and welcome to Titan v1.4.0-Dev.
```


this message is just in titan.log
```
[08:07:15 DEBUG] Titan @ 1 - Startup: Loading Serilog <-> Common Logging Bridge.
[08:07:15 DEBUG] Titan @ 1 - Startup: Loading Quartz.NET.
[08:07:16 DEBUG] Titan @ 1 - Startup: Refreshing Steam Universe list.
[08:07:16 DEBUG] Titan @ 1 - Startup: Parsing Command Line Arguments.
[08:07:16 INFORMATION] Titan @ 1 - The arguments --target and --mode were omitted - opening the UI.
```

I get the message Titan.exe is not working and I can choose to start debugging or to close Titan.exe

I think he is trying to open the UI but smth went wrong.
I dont know what the debugging result is :D. He said the problem is smth with frame 4.0? I had to use the codetype v4.6 v4.5 v4.0
As I tried to debug with 3.0 codetyp it said that I have to use 4.0 series or smth
failure with framework 4.x?

**Comment by Marc3842h** [comment]
Do you have .NET 4.6 Framework installed?

**Comment by smurfPrime** [comment]
4.6 installed (first thing I tried to update netframe but its up to date)

> Does a Eto.Forms and Eto.Wpf file exist?
Titan v1.5.0-folder:
Eto.dll
Eto.Wpf.dll

Eto.Forms is missing

**Comment by Marc3842h** [comment]
I'll give you after I'm back fron Vacations a Eto.WinForms build instead of Eto.Wpf

**Comment by smurfPrime** [comment]
Using 1.4.0 first of all ;)  

thanks for ur nice work

**Comment by Marc3842h** [comment]
Hi, I changed the arguments passed to the CS:GO Game Coordinator in commit 2cc5f39. Could you try out with the latest build built from source?

**Comment by raspbianlike** [comment]
This discussion seems inactive, how about we close it?
