### ISSUE TITLE
where did i go wrong?

### ISSUE THREAD

**Issue by superhumanz** [Marc3842h/Titan#32]
00:26:55 [Main] DEBUG Titan - Startup: Loading Serilog <-> Common Logging Bridge.
00:26:55 [Main] DEBUG Titan - Startup: Loading Quartz.NET.
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Default Quartz.NET properties loaded from embedded resource file
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Using default implementation for object serializer
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Using default implementation for ThreadExecutor
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Quartz Scheduler v.2.5.0.0 created.
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - RAMJobStore initialized.
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Scheduler meta-data: Quartz Scheduler (v2.5.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler 'DefaultQuartzScheduler' initialized
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Quartz scheduler version: 2.5.0.0
00:26:55 [Main] INFORMATION Quartz.NET Scheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
00:26:55 [Main] DEBUG Titan - Startup: Refreshing Steam Universe list.
00:26:55 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:26:55 [Main] DEBUG Titan - Startup: Parsing Command Line Arguments.
00:26:55 [Main] INFORMATION Titan - The arguments --target and --mode were omitted - opening the UI.
00:26:55 [Main] DEBUG Titan - Startup: Loading UI Manager, Victim Tracker, Account Manager and Ban Manager.
00:26:56 [Main] DEBUG AccountManager - Titan Account Manager initialized on 12:26 AM. (6.3636712016292E+17)
00:26:56 [Main] DEBUG Titan - Startup: Registering Shutdown Hook.
00:26:56 [Main] DEBUG Titan - Startup: Parsing accounts.json file.
00:26:56 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 1 triggers
00:26:56 [Main] DEBUG Quartz.NET Scheduler - Producing instance of Job 'Titan.Victim Tracker Job', class=Titan.Logging.VictimTracker
00:26:56 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:26:56 [Main] DEBUG Quartz.NET Scheduler - Calling Execute on job Titan.Victim Tracker Job
00:26:56 [DefaultQuartzScheduler_QuartzSchedulerThread] DEBUG VictimTracker - Checking all victims if they have bans on record.
00:26:56 [DefaultQuartzScheduler_QuartzSchedulerThread] INFORMATION VictimTracker - Victims: []
00:26:56 [Main] DEBUG Quartz.NET Scheduler - Trigger instruction : NoInstruction
00:26:56 [Main] DEBUG GC - lionairsg (Protected) - Successfully initialized account object for lionairsg.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: lionairsg / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - SenayanJKT (Protected) - Successfully initialized account object for SenayanJKT.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: SenayanJKT / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - _fiqizaidi (Protected) - Successfully initialized account object for _fiqizaidi.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: _fiqizaidi / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - fiqizaidi__ (Protected) - Successfully initialized account object for fiqizaidi__.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: fiqizaidi__ / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - fiqizaidi___ (Protected) - Successfully initialized account object for fiqizaidi___.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: fiqizaidi___ / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - fiqi_zaidi (Protected) - Successfully initialized account object for fiqi_zaidi.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: fiqi_zaidi / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - fiqisyaza (Protected) - Successfully initialized account object for fiqisyaza.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: fiqisyaza / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - fiqisyaza0804 (Protected) - Successfully initialized account object for fiqisyaza0804.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: fiqisyaza0804 / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - fiqizaidi_ (Protected) - Successfully initialized account object for fiqizaidi_.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: fiqizaidi_ / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - fiqisyaza8 (Protected) - Successfully initialized account object for fiqisyaza8.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: fiqisyaza8 / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] DEBUG GC - kemangicon (Protected) - Successfully initialized account object for kemangicon.
00:26:56 [Main] DEBUG AccountManager - Found account (specified in index #0): Username: kemangicon / Password:  / Sentry: false / Enabled: true
00:26:56 [Main] INFORMATION AccountManager - Account file has been successfully parsed. 11 accounts have been parsed. Details: [{Index=0, Count=11}]
00:26:56 [Main] DEBUG AccountManager - Using index #0 for botting.
00:26:56 [Main] DEBUG Titan - Initializing Forms...
00:26:56 [Main] DEBUG Titan - Startup: Loading Web API Key
00:26:56 [Main] DEBUG WebAPIKeyResolver - Using Steam API Key null for the Steam Web API.
00:26:56 [Main] INFORMATION Titan - Hello and welcome to Titan v1.4.0-Dev.
00:27:22 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:27:25 [Main] DEBUG APIKeyForm - Successfully set Web API key to http://steamcommunity.com/profiles/76561198188875342/.
00:27:25 [Main] INFORMATION APIKeyForm - Successfully closed API key form.
00:27:48 [Main] WARNING General - Could not convert 8 to a valid Match ID. Trying to resolve the the Match ID in which the target is playing at the moment.
00:27:48 [Main] DEBUG ThreadManager - Starting Match ID resolving thread for STEAM_0:0:114304807 using account lionairsg.
00:27:48 [Main] DEBUG GC - lionairsg (Protected) - Sentry has been activated for this account. Checking if a sentry file exists and hashing it...
00:27:48 [Main] DEBUG GC - lionairsg (Protected) - Sentry file found. Hashing...
00:27:48 [Main] DEBUG GC - lionairsg (Protected) - Hash for sentry file found: I???K???[????#?E
00:27:48 [Main] ERROR Titan - A error occured when trying to get the Ban Information for 76561198188875342.
System.Net.WebException: The remote server returned an error: (403) Forbidden.

Server stack trace:
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at SteamKit2.WebAPI.AsyncInterface.<>c__DisplayClass6_0.<Call>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Exception rethrown at [0]:
   at SteamKit2.WebAPI.Interface.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , UInt64 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Titan.Bans.BanManager.GetBanInfoFor(SteamID steamID)
00:27:48 [Main] WARNING Titan - Did not receive ban informations for 76561198188875342. Skipping...
00:27:49 [Main] DEBUG GC - lionairsg (Protected) - Successfully logged in. Checking for any VAC or game bans...
00:27:49 [Main] ERROR Titan - A error occured when trying to get the Ban Information for 76561198374008640.
System.Net.WebException: The remote server returned an error: (403) Forbidden.

Server stack trace:
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at SteamKit2.WebAPI.AsyncInterface.<>c__DisplayClass6_0.<Call>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Exception rethrown at [0]:
   at SteamKit2.WebAPI.Interface.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , UInt64 )
   at Titan.Bans.BanManager.GetBanInfoFor(SteamID steamID)
00:27:49 [Main] WARNING Titan - Did not receive ban informations for 76561198374008640. Skipping...
00:27:49 [Main] DEBUG GC - lionairsg (Protected) - Registering that we're playing CS:GO...
00:27:51 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:27:54 [Main] DEBUG GC - lionairsg (Protected) - Successfully registered playing CS:GO. Sending client hello to CS:GO services.
00:27:54 [Main] DEBUG GC - lionairsg (Protected) - Successfully received client hello from CS:GO services. Sending Live Game Request...
00:27:55 [Main] INFORMATION GC - lionairsg (Protected) - Received live game Match ID: 3223558274896887983
00:28:16 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:28:39 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:29:08 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:29:36 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:30:05 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers
00:30:31 [Main] DEBUG Quartz.NET Scheduler - Batch acquisition of 0 triggers

**Comment by 1n9i9c7om** [comment]
> 00:27:25 [Main] DEBUG APIKeyForm - Successfully set Web API key to http://steamcommunity.com/profiles/76561198188875342/.

This might be the root of your issue. You need to go on this page and generate an API key (domain name doesn't matter): http://steamcommunity.com/dev/apikey

**Comment by superhumanz** [comment]
Hey thanks got it fixed , but yesterday i reportbot a rager without matchid he didn't get banned though

**Comment by Marc3842h** [comment]
I personally had less success without Match than with. Try to wait longer (some people are like ~2 days before they get banned) or try to report with Match ID.

**Comment by Marc3842h** [comment]
User didn't respond within 7 days, closing this issue.
