### ISSUE TITLE
Account List Gui crash

### ISSUE THREAD

**Issue by Slatprh** [Marc3842h/Titan#33]
## Description

GUI Crashes on the second open of account list.

## Reproduction Steps

1. < Open Account List and Close it >
2. < Attempt to open it again >

## Errors

```bash
< N/A >

```

## System Information

**Operating System**: < Windows 10 >
**Titan version**: < Latest Windows release>

**Comment by Marc3842h** [comment]
Are there any errors in console?

**Comment by Slatprh** [comment]
Nope, just comes up with "Titan is not responding" window.

**Comment by Marc3842h** [comment]
I'll look into it. It may be a problem with Eto.Forms if it doesn't output a error.

**Comment by Marc3842h** [comment]
May I ask if Eto.Forms.dll and Eto.Wpf.dll files exist

**Comment by Slatprh** [comment]
Yep

https://philslater.tk/uploads/2017_07/Friday-July-28_975.png

**Comment by smurfPrime** [comment]
same problem like I got ;)     Eto.Forms.dll missing ^^

**Comment by Marc3842h** [comment]
Yea the actual file is named Eto.dll, I just remembered incorrect.

**Comment by raspbianlike** [comment]
This seems inactive, right?
