### ISSUE TITLE
What's "sentry"?

### ISSUE THREAD

**Issue by sumgui316** [Marc3842h/Titan#34]
Hi!

Everything works fine. (I'm on Win7 btw).

My question is: I can see "Sentry: false" in accounts. What is it? I didn't turned it on yet because I can see what it does.

Thank you, and keep up the great work.

**Comment by Slatprh** [comment]
Sentry is used if your accounts have steamguard enabled. Set sentry to enabled then add the secretkey in the JSON file.

**Comment by Marc3842h** [comment]
Exactly what Slatphr has written. If you don't include `secret`, it will ask for SteamGuard code upon reporting.

**Comment by sumgui316** [comment]
But hmmm, what should I put as "Shared Secret for SteamGuard"? Because if I understand, you made it that it automaticly generates 2FA Steam Guard code but what's a Shared Secret for SteamGuard?

Is it possible that I don't have the latest version? Because I noticed on the screenshot of the release 1.5, there is a "EDIT" menu. Which I don't  have?!

I only have 9 alt, I wish I could afford 2 more... But If me (on my main) and a friend report someone + 9 bots, does it work?

Anyways, this is a very impressive piece of work, I have to admit.

**Comment by Marc3842h** [comment]
If you have SteamGuard enabled, you can extract the Shared Secret from the SteamGuard app.

Iirc it us possible with a Jailbreak on iOS and on Android w/o Root.

**Comment by Marc3842h** [comment]
User didn't respond within 7 days, closing this issue.
