### ISSUE TITLE
add more accounts

### ISSUE THREAD

**Issue by jtmkungfu** [Marc3842h/Titan#35]
## Description

i dont know how to add more accounts than those made in the template for accounts.

## Reproduction Steps

1. make file and replace username and password with spots there
2. dont know how to get more places for username and password
## System Information

os windows 8.1
**Titan version**: 1.5.0

**Comment by smurfPrime** [comment]
maybe this will help you ;) it helped me

copy the text and try to add more lines ;) it will show what you did wrong
http://www.json-generator.com/

**Comment by jtmkungfu** [comment]
i got it to no errors but then when i use it for the acounts.json it just crashes titan and says titan has stopped working

**Comment by Marc3842h** [comment]
Error when it crashes? To add a account, just copy from `{` to `}`, to the next array block and fill in the corresponding values.

**Comment by smurfPrime** [comment]
I had a problem that I changed the .json file into a .txt file

maybe u got the same problem?
thats why I used http://www.json-generator.com/ to be sure its a .json file

**Comment by Marc3842h** [comment]
User didn't respond within 7 days, closing this issue.
