### ISSUE TITLE
[Main] ERROR AccountManager 

### ISSUE THREAD

**Issue by thestranger00** [Marc3842h/Titan#36]
on every accounts Index #1 #2 #3 etc  there's always 1,2 or more accounts that gives error so usually 8-9 accounts works for reporting/commends on each INDEX (with 11 accounts ofc)

THIS ERROR 🔴 : **[Main] ERROR AccountManager - Could not start botting for account XYZ: An item with the same key has already been added.**

After that error It does check if account has VAC or Game ban 

**XYZ (Unprotected) - Successfully logged in. Checking for any VAC or game bans...**

After that 

**XYZ (Unprotected) - Successfully logged off from Steam: LogonSessionReplaced**
**XYZ (Unprotected) - Disconnected from Steam. Retrying in 5 seconds... (5/5)**

Than eventually only 10 reports sent instead of 11 (if only have 1 error if 2 then 9 reports and so on...but mostly its one account every INDEX)

I'm not sure why it is :/ I tried manually login on steam client and it works just fine but on Titan it gives error

All accounts are clean without any kind of ban or restrictions with CSGO on all of them.... and not using any IDLE program.

**Comment by Marc3842h** [comment]
It looks like accounts are defined twice. Please check for duplicates in your accounts.json.

**Comment by thestranger00** [comment]
I did checked and there's no duplicates.

**Comment by smurfPrime** [comment]
check for correct syntax
http://www.json-generator.com/

**Comment by thestranger00** [comment]
how to  correct syntax ?

**Comment by smurfPrime** [comment]
maybe u failed with {   [

**Comment by TheRhanderson** [comment]
I can report with only 10 accounts too. Everytime I always see only 10 confirmation codes, never 11. For commends, works fine. But not for reportbot. I have 10 index, all right, but it happens too

**Comment by Marc3842h** [comment]
The LoginSessionReplaced error only occurs if you're logging in with the same `logonID` and the same public IP adress. After I'm back from vacations, I'll implement random logon ID setting. 

Thanks for your issue report.

**Comment by Marc3842h** [comment]
I fixed this issue in 65c6b4a, please try with the latest source code release if it works.

**Comment by thestranger00** [comment]
same issue, still using only 10 accounts. Always getting this error

10:19:13 [Main] ERROR AccountManager - Could not start botting for account XYZ: An item with the same key has already been added.

for first account.

**Comment by Marc3842h** [comment]
I fixed the logonID issue when trying to login too fast using the same IP. Are you sure there are no duplicated?

**Comment by thestranger00** [comment]
I'm 100% sure no duplicates

**Comment by thestranger00** [comment]
It's always the first account with every index

**Comment by Marc3842h** [comment]
Please open another issue for this, I'll look into it.
