### ISSUE TITLE
Adding more Names

### ISSUE THREAD

**Issue by TechniChief** [Marc3842h/Titan#37]
Adding more names

Hello i want to add 11 accounts but it dont work it says in the console just 3 names

## Reproduction Steps

1. < When i add more accounts i only says the first copied account not the added accounts >
2. <Please someone give me a copied line with 11 accounts to paste >

Windows 10 System
Titan Version 1.5.0

**Comment by thestranger00** [comment]
,
        {
            // Index 2
            "accounts": [
               {
                    "username": "account1",
                    "password": "uuu",
                    "enabled": true,
                    "sentry": false,
                },
                {
                    "username": "account2",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account3",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account4",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account5",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account6",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account7",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account8",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account9",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account10",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account10",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                }
            ]
        },
        {
            // Index 3
            "accounts": [
               {
                    "username": "account1",
                    "password": "uuu",
                    "enabled": true,
                    "sentry": false,
                },
                {
                    "username": "account2",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account3",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account4",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account5",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account6",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account7",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account8",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account9",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account10",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                },
                {
                    "username": "account10",
                    "password": "uuu",
                    "enabled": true, // May be omitted if you want set it to default value (true)
                    "sentry": false, // May be omitted if you want set it to default value (false)
                }
            ]
        }
    ]
}

**Comment by TechniChief** [comment]
Thank you Very Much

**Comment by thestranger00** [comment]
I thought you'll figure it out but anyway 

here you go. Enjoy

https://pastebin.com/juw9gJYW

**Comment by TechniChief** [comment]
Thanks i did it like you said it but probably i made mistakes thanks

**Comment by Marc3842h** [comment]
Run your accounts.json thought a Json validator and look for errrors.

**Comment by TechniChief** [comment]
A question do all bot acc must have csgo cuz when i tried to report bot somoene it said something like unable or incorrect but its all correct

**Comment by Marc3842h** [comment]
Yes.

**Comment by TechniChief** [comment]
its waste of money

**Comment by thestranger00** [comment]
lol

**Comment by TechniChief** [comment]
i need 11 copies of csgo bruh

**Comment by Marc3842h** [comment]
Do it like me. Get 5 Friends, everybody buys 2 CS:GO accounts and everybody of them can also use it. Getting cheaters banned and free commends isn't a waste imo when you only paid 8$. When Valve ever fixes thesr Bots, you coulf just sell these accounts or smth.

**Comment by Marc3842h** [comment]
User didn't respond within 7 days, closing this issue.
