### ISSUE TITLE
Little suggestion

### ISSUE THREAD

**Issue by sumgui316** [Marc3842h/Titan#38]
Hey,

You know, it could be useful if we could also use Titan to "idlebot" in CSGO's menu to grind playtime a little.
Maybe?!

**Comment by Marc3842h** [comment]
I don't know if that is too much for Titan as it is planned to just be a Report and Commend Bot and not a AllIn1Bot. I'll think about it.

**Comment by TechniChief** [comment]
Here You Go http://www.steamidlemaster.com/
