### ISSUE TITLE
accounts.json

### ISSUE THREAD

**Issue by 123top** [Marc3842h/Titan#4]
Can somebody give me an example how the accounts.json should look like?

**Comment by 123top** [comment]
I don't know how accounts.json should look like. 
[something else-->] Just an idea, you can grab the matchid of a match during the match. Maybe implement this feature?

**Comment by Marc3842h** [comment]
The accounts.json should look into the following format: 
```json
{
  "indexes": [
    // Put here a array of indexes with accounts. Starting with { and ending with a }: use a , to split.
    {
      "accounts": [
        // Put in here a array of accounts. Starting with a { and ending with a }: use a , to split.
        {
          "username": "usernamehere",
          "password": "passwordhere",
          "enabled": true, // Set to false if the account should not be used for reporting
          "sentry": false, // Set to true if the account has Steam Guard enabled
        }
      ]
    }
  ]
}
```
If you trust me, you can add me on steam and give me a list of your accounts, I'll convert them into a accounts.json file.

Also, i'm not going to let Titan read any memory from the current CS:GO process as it may risk a VAC ban and only works on Windows (not for Linux). If you are in a Match with somebody that you would like to report, just leave the Match ID field blank. Overwatch will automaticly grab the latest game of the player, which he currently is in.

**Comment by 123top** [comment]
got it, thx. how does the banchecker works?

**Comment by Marc3842h** [comment]
You input the Steam Web API key and when you press the "Bomb" key, the Ban Checker checks using the Steam Web API if the bots and the target have VAC or game bans on record.

**Comment by 123top** [comment]
Okay just one more thing. If I get it right if I report somebody the Bot checks all previous reported player?

**Comment by Marc3842h** [comment]
No. The bot doesn't keep a history of players that you report botted. Titan just checks if the bot accounts that you use to report with have a ban on record.

**Comment by 123top** [comment]
kinda useless, the feature of tracking player would be nice, maybe add?

**Comment by Marc3842h** [comment]
Well it helps lazy people. I'll put your idea on the TODO list.

**Comment by 123top** [comment]
I asked a mate and he told me you can get the matchid as a viewer and it is possible to grab it that way during the match. Can you look into it? btw can I add you in steam?

**Comment by Marc3842h** [comment]
Ofcourse you can add me on Steam, i'll look into itm
