### ISSUE TITLE
Why timeout happens to account when reporting?

### ISSUE THREAD

**Issue by kranvagn2k** [Marc3842h/Titan#40]
http://imgur.com/a/z5YCJ

Only one reporting was completed today and all of the other reporting was failed because of the timeout error.

**Comment by thestranger00** [comment]
That happens to me as well but not that often.

**Comment by kranvagn2k** [comment]
I happen to me almost everytime...

**Comment by Marc3842h** [comment]
Are you able to connect with any other SteamKit-based automation software like ArchiSteamFarm? The "Fail" error is new, I'll investigate.

**Comment by kranvagn2k** [comment]
Yes, I connected to Idle Master and HourBooster with those accounts before.

**Comment by TheCryzy** [comment]
I have this problem too, i cant commend anyone. I tried it with my 2 accounts.
