### ISSUE TITLE
question with report wait

### ISSUE THREAD

**Issue by jtmkungfu** [Marc3842h/Titan#41]
when you report someone i saw you said you need to wait 12 hours instead of the 6 listed but does that then reset if you try and report before the 12 hours or does it just finish how it should have

**Comment by smurfPrime** [comment]
It is resetting each time u try to report

Had the same question/problem

**Comment by jtmkungfu** [comment]
thank you i wasnt sure if i needed to try so i started setting a timer

**Comment by Marc3842h** [comment]
As smurfPrime said, it will reset when you report bot again. I can change that in future versions if you want.
