### ISSUE TITLE
Dunno how to fix this, what ive done wrong?

### ISSUE THREAD

**Issue by maplinx** [Marc3842h/Titan#42]
This is my first time trying Titan
what ive done wrong here?

Newest version of Titan 1.5.0

![image](https://user-images.githubusercontent.com/29700644/28859653-d45de35c-7782-11e7-829f-d890b8af8f1d.png)
![image](https://user-images.githubusercontent.com/29700644/28859666-e3c30886-7782-11e7-884f-dbdf474095ba.png)

**Comment by Marc3842h** [comment]
Yea you need to fix your accounts.json. Checkout https://jsonlint.com/, paste it into there and look for errors. Then fix them.

**Comment by Apostropheqq** [comment]
[kisak](https://cdn.discordapp.com/attachments/331877835784323092/333717032971534346/gay.png)

**Comment by maplinx** [comment]
nope, testing out with 11 accounts
me and my friends cant do it too.

![image](https://user-images.githubusercontent.com/29700644/28860537-3fea1b96-7787-11e7-94b6-01128c4c1f32.png)

![image](https://user-images.githubusercontent.com/29700644/28860498-191f29c0-7787-11e7-985e-b2f7c2852eeb.png)

**Comment by maplinx** [comment]
I'm running on Windows 10 build 15063 x64
![image](https://user-images.githubusercontent.com/29700644/28861103-9cefa32c-7789-11e7-83f4-aff79ac9c309.png)

**Comment by maplinx** [comment]
Case closed, its fixed, I should not change accounts into #01.
thanks
