### ISSUE TITLE
victim.json problem

### ISSUE THREAD

**Issue by Faldi767** [Marc3842h/Titan#43]
Why my victim.json still empty after report someone using 11 acc ? is that a bug from the program ?
I'm using Windows 10 64bit and latest Titan version

**Comment by Marc3842h** [comment]
Did you close Titan via Process Manager? Titan only saves when you shut it down gracefully using the TrayIcon.

**Comment by Faldi767** [comment]
i never close Titan via Task Manager, i always close Titan from Tray at right corner side and its still not save victim.json after reporting someone

**Comment by Marc3842h** [comment]
This is odd. Do you receive a "Saving victims.json" or something similar in the console?

**Comment by Faldi767** [comment]
umm not really watch that log, gonna try report someone again soon and take some log

**Comment by Faldi767** [comment]
![image](https://user-images.githubusercontent.com/22939114/28923657-f25b6d1e-7888-11e7-9898-e3fd9851d905.png)
its still not saving after i try to report someone

**Comment by Marc3842h** [comment]
I mean after you have closed Titan. You can find the log file in the Titan folder.

**Comment by Faldi767** [comment]
[21:14:20 DEBUG] VictimTracker @ 2 - Successfully wrote Victim file.
still no save

**Comment by Faldi767** [comment]
Report is working with full confirmation ID, the problem is only at victims.json that not input any data after i report someone so the tracker cant work properly

**Comment by Faldi767** [comment]
can u give me the example format of victim.json ? so i can add them manually to make tracker work until this problem solved

**Comment by Marc3842h** [comment]
I don't have one right now here that has been filled out by Titan itself, but the snippet down below should work (if I'm not autistic and remembered incorrectly):

```json
{
   "victims": [
      {
         "steamid": 76561198224231904, 
         "timestamp": 0
      }
   ]
}
```
**SteamID**: SteamID64 of botted target
 **Timestamp**: This is not important, it will just display when you botted the player. This is in [Ticks](https://msdn.microsoft.com/en-us/library/system.datetime.now.aspx).

**Comment by thestranger00** [comment]
Same issue it never give any kind of notification if target gets BAN and i just checked victim.json and its empty so i guess that was the issue.

**Comment by Faldi767** [comment]
problem solved by build from source manual, but the releases one that already include titan.exe still bugged

**Comment by jtmkungfu** [comment]
When i got from the zip it works for me if i close through the task bar

**Comment by Faldi767** [comment]
umm i see, but now im using from source bcuz titan that i got from the zip bugged on my pc dont know why
