### ISSUE TITLE
IMPORTANT: Official Titan Report & Commend Bot Discord

### ISSUE THREAD

**Issue by Marc3842h** [Marc3842h/Titan#45]
If you want faster help, join the Discord using the Badge below:

[![Discord](https://img.shields.io/discord/342308069897928706.svg?label=discord)](https://discord.me/titanbot)

You can ask your question like this for example:
`@My Question Is: How to fill out the accounts.json`

**Comment by raspbianlike** [comment]
wont fix

**Comment by Marc3842h** [comment]
actually not fixable, still reopen cuz important

**Comment by Marc3842h** [comment]
The Discord is linked in the README.md file. That is enough reference for now.
