### ISSUE TITLE
one account not working

### ISSUE THREAD

**Issue by jtmkungfu** [Marc3842h/Titan#46]
so recently when im reporting someone i have all my accounts doing exactly as their supposed to but then there is one that logs on to steam then disconnects right away. im not sure if this could be from me doing the reporting from my laptop or whatever since on vacation, but i only disconnects on report not commend.

**Comment by thestranger00** [comment]
Same issue.

**Comment by jtmkungfu** [comment]
I found out its just what ever is first in the list of accounts so i left the top one blank and the account with no information was reconnecting

**Comment by Marc3842h** [comment]
Looks like OP fixed it, going to close this.
