### ISSUE TITLE
Index accounts and tracker issue

### ISSUE THREAD

**Issue by thestranger00** [Marc3842h/Titan#47]
Every Index only 10 accounts are being used for REPORTING only (Commends work just fine)
Its usually the first account from every Index which gets timed out and session unavailable.

And the other issue is with TRACKING.. no matter how you close titan.exe (normally from task bar or clicking on close "x" icon on application) It just didn't save anything on "victims" Its always 0 KB in size.

here's the old issue thread - https://github.com/Marc3842h/Titan/issues/36#issuecomment-318638484

**Comment by thestranger00** [comment]
**## I found a workaround for all accounts not being used**

**Simply adding one fake account user:pass in first of every Indexes** (total accounts will be 12)

**Comment by Marc3842h** [comment]
This looks like it has to do with resolving of current Match ID, will look into it.
