### ISSUE TITLE
Problem [CommendBOT]

### ISSUE THREAD

**Issue by nivek1ng** [Marc3842h/Titan#49]
## Description

My problem, is commend bot dont work. when i commend me... i open the game and i dont recive any commend, i turn off steam guard.. i wait 24 hours per commend.. and dont work 

## Reproduction Steps

1. before and after login (in game) : http://i.imgur.com/ibSfiXL.png
2. commend me : http://i.imgur.com/t8Guc08.png
3. log : http://i.imgur.com/3BBcCd9.png
4. "sucessfully" : http://i.imgur.com/c1KVvSX.png  

## System Information

**Operating System**: < Windows 10>
**Titan version**: <1.5.0 >

**Comment by Marc3842h** [comment]
Are you able to provide log files (from the `logs` folder) and **debug** network packets (from the `debug` folder, please don't send these network packets publicly - send them privately to me over [Discord](discord.me/TitanBot) or [Steam](steamcommunity.com/id/Marc3842h))?

**Comment by Marc3842h** [comment]
Hi, I changed the arguments passed to the CS:GO Game Coordinator in commit 2cc5f39. Could you try out with the latest build built from source?

**Comment by nivek1ng** [comment]
Sent you in discord and sent invite of friends :D

**Comment by nivek1ng** [comment]
any solutions?

**Comment by raspbianlike** [comment]
This issue has been resolved via Discord. Closing.
