### ISSUE TITLE
Suggestion: Remove Commends?

### ISSUE THREAD

**Issue by TheRhanderson** [Marc3842h/Titan#5]
It will be nice also

**Comment by Marc3842h** [comment]
Added to the ToDo list, thanks for the suggestion.

**Comment by Marc3842h** [comment]
Your suggestion has been implemented in 3f84287. It will be shipped with v1.5.0. If you can't wait until then, please compile from source.

 Please keep in mind that I'm unable to test this, so please report any issues on a seperate issue here on the issues tracker.

**Comment by Marc3842h** [comment]
The usage of this suggestion has been changed. The new UI (#17) has removed the "Un-Commend" feature. If you want to remove all commends, you need to **uncheck** the checkboxes from the Commend menu, like this:
![nnnn](https://user-images.githubusercontent.com/24739711/27192756-c02eb678-51fc-11e7-995f-87fe67356966.png)

This change will go into effect with v1.5.0.
