### ISSUE TITLE
Pls fix

### ISSUE THREAD

**Issue by DankPaster** [Marc3842h/Titan#50]
This repo started thermonuclear war with north korea and and us, Pls fixerino kthnks.

**Comment by thestranger00** [comment]
kek

**Comment by Marc3842h** [comment]
won't fix /closed

**Comment by DankPaster** [comment]
wow bad support

**Comment by DankPaster** [comment]
Reported & Deported

**Comment by Marc3842h** [comment]
I'm legal sir I swear
