### ISSUE TITLE
Error after complicating in powershell

### ISSUE THREAD

**Issue by KaciPL** [Marc3842h/Titan#57]
command used: powershell.exe -noprofile -executionpolicy bypass -file .\build.ps1

Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Compiling build script...

========================================
Clean
========================================
Executing task: Clean
Cleaning directory C:/Users/KaciPL/Desktop/Titan-master/Titan/bin/Release
Finished executing task: Clean

========================================
Restore-NuGet-Packages
========================================
Executing task: Restore-NuGet-Packages
MSBuild auto-detection: using msbuild version '15.4.8.50001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Wszystkie pakiety wymienione w packages.config zostały już zainstalowane.
Finished executing task: Restore-NuGet-Packages

========================================
Build
========================================
Executing task: Build
Microsoft (R) Build Engine 15.4.8.50001 dla platformy .NET Framework
Copyright (C) Microsoft Corporation. Wszelkie prawa zastrzeżone.

Projekty w tym rozwiązaniu są tworzone po kolei. Aby umożliwić tworzenie równoległe, dodaj przełącznik "/m".
Kompilacja rozpoczęła się 2017-11-02 13:25:02.
Projekt "C:\Users\KaciPL\Desktop\Titan-master\Titan.sln" w węźle 1 (elementy docelowe: Build).
ValidateSolutionConfiguration:
  Tworzenie konfiguracji rozwiązania "Release|Any CPU".
Projekt "C:\Users\KaciPL\Desktop\Titan-master\Titan.sln" (1) kompiluje "C:\Users\KaciPL\Desktop\Titan-master\Titan\Titan.csproj" (2) w węźle 1 (domyślne elementy docelowe).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.targets(322,5): error MSB4019: Nie można odnaleźć zaimportowanego projektu "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets". Upewnij się, że ścieżka w deklaracji <Import> jest poprawna oraz że plik istnieje na dysku. [C:\Users\KaciPL\Desktop\Titan-master\Titan\Titan.csproj]
Kompilowanie projektu "C:\Users\KaciPL\Desktop\Titan-master\Titan\Titan.csproj" wykonane (domyślne elementy docelowe) - NIEPOWODZENIE.
Projekt "C:\Users\KaciPL\Desktop\Titan-master\Titan.sln" (1) kompiluje "C:\Users\KaciPL\Desktop\Titan-master\TitanTest\TitanTest.csproj" (3) w węźle 1 (domyślne elementy docelowe).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.targets(322,5): error MSB4019: Nie można odnaleźć zaimportowanego projektu "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets". Upewnij się, że ścieżka w deklaracji <Import> jest poprawna oraz że plik istnieje na dysku. [C:\Users\KaciPL\Desktop\Titan-master\TitanTest\TitanTest.csproj]
Kompilowanie projektu "C:\Users\KaciPL\Desktop\Titan-master\TitanTest\TitanTest.csproj" wykonane (domyślne elementy docelowe) - NIEPOWODZENIE.
Kompilowanie projektu "C:\Users\KaciPL\Desktop\Titan-master\Titan.sln" wykonane (elementy docelowe: Build) - NIEPOWODZENIE.

Kompilacja NIE POWIODŁA SIĘ.

"C:\Users\KaciPL\Desktop\Titan-master\Titan.sln" (element docelowy Build) (1) ->
"C:\Users\KaciPL\Desktop\Titan-master\Titan\Titan.csproj" (domyślny element docelowy) (2)->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.targets(322,5): error MSB4019: Nie można odnaleźć zaimportowanego projektu "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets". Upewnij się, że ścieżka w deklaracji <Import> jest poprawna oraz że plik istnieje na dysku. [C:\Users\KaciPL\Desktop\Titan-master\Titan\Titan.csproj]

"C:\Users\KaciPL\Desktop\Titan-master\Titan.sln" (element docelowy Build) (1) ->
"C:\Users\KaciPL\Desktop\Titan-master\TitanTest\TitanTest.csproj" (domyślny element docelowy) (3)->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Microsoft.CSharp.CurrentVersion.targets(322,5): error MSB4019: Nie można odnaleźć zaimportowanego projektu "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets". Upewnij się, że ścieżka w deklaracji <Import> jest poprawna oraz że plik istnieje na dysku. [C:\Users\KaciPL\Desktop\Titan-master\TitanTest\TitanTest.csproj]

    Ostrzeżenia: 0
    Liczba błędów: 2

Czas, który upłynął: 00:00:00.70

**Comment by Marc3842h** [comment]
What OS do you have installed and do you have Visual Studio 2017 installed? Please follow the issue template the next time.

**Comment by KaciPL** [comment]
I have Visual Studio 2017 community
Windows 7 64bit

**Comment by Marc3842h** [comment]
I'm ot able to fully translate the error messages, could you please translate them for me?

**Comment by KaciPL** [comment]
How i can change language in powershell?

**Comment by Marc3842h** [comment]
Try to change your systems language

**Comment by raspbianlike** [comment]
This seems inactive and Im not able to build on Win7 too, but who cares. If there are problems, please open   a new issue. Closing
