### ISSUE TITLE
Commend Issue

### ISSUE THREAD

**Issue by TheRhanderson** [Marc3842h/Titan#6]
I have 70 saved accounts and Titan is only sending 55 accounts, ignoring the rest, and I can not identify the reason in the console

**Comment by Marc3842h** [comment]
This ist most likely because of the Steam Rate Limit, could you please send all your logs in the `logs` directory as .zip? Please keep in mind that **AccountManager** log contains **login username & password**, so remove them before posting them publicly.

**Comment by TheRhanderson** [comment]
I'll send the log later
From what I saw, Titan started straight to the accounts with Steam Guard off, ignoring the accounts with Steam Guard. And yes, it's true in enabled=

**Comment by Marc3842h** [comment]
For Steam Guard Accounts, you'll need to set to `sentry` to `true` in order for Titan to use the Steam Guard implementation. For Non-Steam Guard Accounts, `sentry` should be default on `false`.

**Comment by TheRhanderson** [comment]
I did the test again, and yes, the error appears:
Unable to logon to account: RateLimitExceeded: RateLimitExceeded

Did you have any suggestions to avoid the problem? If I put 70 accounts, he send about 50. If I put 50, he sends some 30 commends. Thanks in advance

**Comment by Marc3842h** [comment]
Try to commend with ~25 accounts, wait 30 minutes, do it again with ~25 accounts and so on. I can't fix the Steam Rate Limit, I'm sorry.

**Comment by Marc3842h** [comment]
User hasn't replied in 7 days, closing this issue for now. Please reopen if needed.
