### ISSUE TITLE
TITAN IS B1G RAT WTF!!!!!

### ISSUE THREAD

**Issue by b1gpaster** [Marc3842h/Titan#67]
I HAD BUILT TITAN ON MY WINDOWS MACHINE AND I NOTICED MY INTERNET UPLOAD GETTING SLOWER IT TURNS OUT TITAN IS A BOTNET IT A VERY ADVANCED BOTNET IT INJECT INTO BIOS SO YOU CAN NEVER GET RID OF IT, IT ALSO USES 100% OF MY GPU TO MINE BITCOINS WHEN I AM GONE NEVER INSTALL A TITAN SOFTWARES EVER IT WILL DESTROY UR PC!!!!!!111!!!

**Comment by Marc3842h** [comment]
Please follow the **[Contributor Covenant Code of Conduct](https://github.com/Marc3842h/Titan/blob/master/CODE_OF_CONDUCT.md)** before dicussing and contributing to the Titan repository and the issues section.
