### ISSUE TITLE
MARC IS A WEEB

### ISSUE THREAD

**Issue by cheddar-cheeze** [Marc3842h/Titan#68]
## Description

Marc is a weeb

## Reproduction Steps
 BIg otaku talks about anime

## Errors
 Cd hentai

## System Information

**Operating System**: anime linux
**Titan version**:no u

**Comment by Marc3842h** [comment]
Please follow the **[Contributor Covenant Code of Conduct](https://github.com/Marc3842h/Titan/blob/master/CODE_OF_CONDUCT.md)** before dicussing and contributing to the Titan repository and the issues section.
