### ISSUE TITLE
Valve problem - Commend bot

### ISSUE THREAD

**Issue by TheRhanderson** [Marc3842h/Titan#69]
Is there someone else who is having problems while commending yesterday and today? The cooldown of 12 hours appears to have been changed or is now very relative. From everyone who i tried since yesterday did not receive the amount of commend correctly.

This does not tend to be a Titan problem, it's just a discussion post so others who have witnessed this can tell their experiences as well.

And no, isn't a RateLimit issue. Some accounts received a confirmation ID and others not, even waiting for 12 hours.

Strange.. tell your experiences! Ty

**Comment by Marc3842h** [comment]
I tried commending today and it worked fine.

**Comment by sonicrules11** [comment]
Yesterday was Tuesday so I assume they didn't go through because servers went down for maintenance.
