### ISSUE TITLE
Generate auth code by using the shared secret

### ISSUE THREAD

**Issue by 1n9i9c7om** [Marc3842h/Titan#7]
First of all - nice project! :)

It would be cool if the required auth code could be generated automatically if the shared secret is specified in the config (which would be a new field).
[There's already a C# method that does exactly that](https://github.com/geel9/SteamAuth/blob/48c29f7cda315234639d633f98782754dc8a5b91/SteamAuth/SteamGuardAccount.cs#L85), so it should be easy to implement this. The only things needed to generate the code are the shared secret and the current time. 

If not, I'll do that if, for some reason, I'll ever have 11 CS:GO accounts. 😆 

Danke. ;)

**Comment by Marc3842h** [comment]
Will be implemented as soon as I start working again on this project, which is supposedly on the 7th of June.

Thanks for the Graffiti by the way

**Comment by 1n9i9c7om** [comment]
No problem, it was just meant as a joke. ;)

**Comment by Marc3842h** [comment]
Feature implemented, will be shipped with next release (1.5.0). Please compile from source if you want to use it before the release ships.
