### ISSUE TITLE
How can I input "secret" field in accounts.json file?

### ISSUE THREAD

**Issue by willowTank** [Marc3842h/Titan#70]
Hello. Thanks to you about very helpful project.
I have one question. When I edit accounts.json file Where can I get secret field ?
Best Regards
When I report bot I just got this screen. Please explain about it too
![untitled1](https://user-images.githubusercontent.com/24641385/34245048-345acbb8-e663-11e7-9127-74bbc437b320.png)

**Comment by Marc3842h** [comment]
If you want to input a shared secret, you need to edit the accounts.json file and need to input the `secret` field for the corresponding account, like you can see [here](https://github.com/Marc3842h/Titan/blob/master/Titan/accounts.json#L11).

**Comment by willowTank** [comment]
Thanks for your reply
