### ISSUE TITLE
When closing and again opening reportbot, I need to confirm all accs again and enter the info

### ISSUE THREAD

**Issue by JaViLuMa** [Marc3842h/Titan#71]
## Description

When you close the reportbot and then again open it, you need to place all of the info inside again and the Steam Guard resets and then you have to log in to all of the mails again.

## Reproduction Steps

1. Close the rbot??
2. Open the rbot??

## Errors

No errors, just account arent saving.

## System Information

**Operating System**: Windows
**Titan version**: Built from source

**Comment by Marc3842h** [comment]
I pushed a fix for the not saving account data half an hour ago. Did you test with that one?
Also you'd need to re-enter authentification code for Steam Guard _mobile app_ everytime (but not for eMail!)

**Comment by JaViLuMa** [comment]
Tested it and it works. The sentries folder contains sentry for only one acc though. Is that okay?

**Comment by Marc3842h** [comment]
It should contain sentries for all accounts that you inputted a valid Steam Guard code before in.

**Comment by JaViLuMa** [comment]
Okay. So when I shut down the bot and open it all should be saved now?

**Comment by Marc3842h** [comment]
When you re-login into the accounts on the next botting (with a SteamGuard code) it should save them.
