### ISSUE TITLE
Titan not saving API KEY and 2FA 

### ISSUE THREAD

**Issue by kokotko1337** [Marc3842h/Titan#77]
## Description
Titan not saving API KEY and 2FA 

## Reproduction Steps

1. make accounts.json
2. started titan
3. added api key
4. started Commendation for own account
5. closed Titan
6. reopened Titan
7, it needs API key  again
8, id needs 2FA again
## System Information
WINDOWS 10

**Comment by Marc3842h** [comment]
What version of Titan are you using and is the 2FA from the Steam Guard mobile app or from the eMail Guard?
