### ISSUE TITLE
Build from source, using Titan.msi but no results

### ISSUE THREAD

**Issue by MikhaelLauda** [Marc3842h/Titan#92]
I downloaded Titan.msi, and added some account and try to commend
But no results

When i try to run Titan from bin > Release > Titan i got "Close Program" error

**Comment by Marc3842h** [comment]
It seems like you're experiencing the same as in #88 and #89. Users have reported a workaround by downgrading `protobuf-net` NuGet package to version 2.1.0 and then back to the newest. You can do that directly from within Visual Studio after running the `build.ps1` and then running Titan from within Visual Studio.
